package com.ehais.school_weixin.model;

import java.util.ArrayList;
import java.util.List;

public class CmfAdExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public CmfAdExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAd_idIsNull() {
			addCriterion("ad_id is null");
			return (Criteria) this;
		}

		public Criteria andAd_idIsNotNull() {
			addCriterion("ad_id is not null");
			return (Criteria) this;
		}

		public Criteria andAd_idEqualTo(Long value) {
			addCriterion("ad_id =", value, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idNotEqualTo(Long value) {
			addCriterion("ad_id <>", value, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idGreaterThan(Long value) {
			addCriterion("ad_id >", value, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idGreaterThanOrEqualTo(Long value) {
			addCriterion("ad_id >=", value, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idLessThan(Long value) {
			addCriterion("ad_id <", value, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idLessThanOrEqualTo(Long value) {
			addCriterion("ad_id <=", value, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idIn(List<Long> values) {
			addCriterion("ad_id in", values, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idNotIn(List<Long> values) {
			addCriterion("ad_id not in", values, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idBetween(Long value1, Long value2) {
			addCriterion("ad_id between", value1, value2, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_idNotBetween(Long value1, Long value2) {
			addCriterion("ad_id not between", value1, value2, "ad_id");
			return (Criteria) this;
		}

		public Criteria andAd_nameIsNull() {
			addCriterion("ad_name is null");
			return (Criteria) this;
		}

		public Criteria andAd_nameIsNotNull() {
			addCriterion("ad_name is not null");
			return (Criteria) this;
		}

		public Criteria andAd_nameEqualTo(String value) {
			addCriterion("ad_name =", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameNotEqualTo(String value) {
			addCriterion("ad_name <>", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameGreaterThan(String value) {
			addCriterion("ad_name >", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameGreaterThanOrEqualTo(String value) {
			addCriterion("ad_name >=", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameLessThan(String value) {
			addCriterion("ad_name <", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameLessThanOrEqualTo(String value) {
			addCriterion("ad_name <=", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameLike(String value) {
			addCriterion("ad_name like", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameNotLike(String value) {
			addCriterion("ad_name not like", value, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameIn(List<String> values) {
			addCriterion("ad_name in", values, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameNotIn(List<String> values) {
			addCriterion("ad_name not in", values, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameBetween(String value1, String value2) {
			addCriterion("ad_name between", value1, value2, "ad_name");
			return (Criteria) this;
		}

		public Criteria andAd_nameNotBetween(String value1, String value2) {
			addCriterion("ad_name not between", value1, value2, "ad_name");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andRole_idIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRole_idIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRole_idEqualTo(Integer value) {
			addCriterion("role_id =", value, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idNotEqualTo(Integer value) {
			addCriterion("role_id <>", value, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idGreaterThan(Integer value) {
			addCriterion("role_id >", value, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("role_id >=", value, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idLessThan(Integer value) {
			addCriterion("role_id <", value, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idLessThanOrEqualTo(Integer value) {
			addCriterion("role_id <=", value, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idIn(List<Integer> values) {
			addCriterion("role_id in", values, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idNotIn(List<Integer> values) {
			addCriterion("role_id not in", values, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idBetween(Integer value1, Integer value2) {
			addCriterion("role_id between", value1, value2, "role_id");
			return (Criteria) this;
		}

		public Criteria andRole_idNotBetween(Integer value1, Integer value2) {
			addCriterion("role_id not between", value1, value2, "role_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cmf_ad
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cmf_ad
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 05 15:49:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}