package com.ehais.school_weixin.model;

import java.util.ArrayList;
import java.util.List;

public class CmfAssetExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public CmfAssetExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAidIsNull() {
			addCriterion("aid is null");
			return (Criteria) this;
		}

		public Criteria andAidIsNotNull() {
			addCriterion("aid is not null");
			return (Criteria) this;
		}

		public Criteria andAidEqualTo(Long value) {
			addCriterion("aid =", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidNotEqualTo(Long value) {
			addCriterion("aid <>", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidGreaterThan(Long value) {
			addCriterion("aid >", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidGreaterThanOrEqualTo(Long value) {
			addCriterion("aid >=", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidLessThan(Long value) {
			addCriterion("aid <", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidLessThanOrEqualTo(Long value) {
			addCriterion("aid <=", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidIn(List<Long> values) {
			addCriterion("aid in", values, "aid");
			return (Criteria) this;
		}

		public Criteria andAidNotIn(List<Long> values) {
			addCriterion("aid not in", values, "aid");
			return (Criteria) this;
		}

		public Criteria andAidBetween(Long value1, Long value2) {
			addCriterion("aid between", value1, value2, "aid");
			return (Criteria) this;
		}

		public Criteria andAidNotBetween(Long value1, Long value2) {
			addCriterion("aid not between", value1, value2, "aid");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andKeyIsNull() {
			addCriterion("key is null");
			return (Criteria) this;
		}

		public Criteria andKeyIsNotNull() {
			addCriterion("key is not null");
			return (Criteria) this;
		}

		public Criteria andKeyEqualTo(String value) {
			addCriterion("key =", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyNotEqualTo(String value) {
			addCriterion("key <>", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyGreaterThan(String value) {
			addCriterion("key >", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyGreaterThanOrEqualTo(String value) {
			addCriterion("key >=", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyLessThan(String value) {
			addCriterion("key <", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyLessThanOrEqualTo(String value) {
			addCriterion("key <=", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyLike(String value) {
			addCriterion("key like", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyNotLike(String value) {
			addCriterion("key not like", value, "key");
			return (Criteria) this;
		}

		public Criteria andKeyIn(List<String> values) {
			addCriterion("key in", values, "key");
			return (Criteria) this;
		}

		public Criteria andKeyNotIn(List<String> values) {
			addCriterion("key not in", values, "key");
			return (Criteria) this;
		}

		public Criteria andKeyBetween(String value1, String value2) {
			addCriterion("key between", value1, value2, "key");
			return (Criteria) this;
		}

		public Criteria andKeyNotBetween(String value1, String value2) {
			addCriterion("key not between", value1, value2, "key");
			return (Criteria) this;
		}

		public Criteria andFilenameIsNull() {
			addCriterion("filename is null");
			return (Criteria) this;
		}

		public Criteria andFilenameIsNotNull() {
			addCriterion("filename is not null");
			return (Criteria) this;
		}

		public Criteria andFilenameEqualTo(String value) {
			addCriterion("filename =", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotEqualTo(String value) {
			addCriterion("filename <>", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameGreaterThan(String value) {
			addCriterion("filename >", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameGreaterThanOrEqualTo(String value) {
			addCriterion("filename >=", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameLessThan(String value) {
			addCriterion("filename <", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameLessThanOrEqualTo(String value) {
			addCriterion("filename <=", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameLike(String value) {
			addCriterion("filename like", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotLike(String value) {
			addCriterion("filename not like", value, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameIn(List<String> values) {
			addCriterion("filename in", values, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotIn(List<String> values) {
			addCriterion("filename not in", values, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameBetween(String value1, String value2) {
			addCriterion("filename between", value1, value2, "filename");
			return (Criteria) this;
		}

		public Criteria andFilenameNotBetween(String value1, String value2) {
			addCriterion("filename not between", value1, value2, "filename");
			return (Criteria) this;
		}

		public Criteria andFilesizeIsNull() {
			addCriterion("filesize is null");
			return (Criteria) this;
		}

		public Criteria andFilesizeIsNotNull() {
			addCriterion("filesize is not null");
			return (Criteria) this;
		}

		public Criteria andFilesizeEqualTo(Integer value) {
			addCriterion("filesize =", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotEqualTo(Integer value) {
			addCriterion("filesize <>", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeGreaterThan(Integer value) {
			addCriterion("filesize >", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeGreaterThanOrEqualTo(Integer value) {
			addCriterion("filesize >=", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeLessThan(Integer value) {
			addCriterion("filesize <", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeLessThanOrEqualTo(Integer value) {
			addCriterion("filesize <=", value, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeIn(List<Integer> values) {
			addCriterion("filesize in", values, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotIn(List<Integer> values) {
			addCriterion("filesize not in", values, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeBetween(Integer value1, Integer value2) {
			addCriterion("filesize between", value1, value2, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilesizeNotBetween(Integer value1, Integer value2) {
			addCriterion("filesize not between", value1, value2, "filesize");
			return (Criteria) this;
		}

		public Criteria andFilepathIsNull() {
			addCriterion("filepath is null");
			return (Criteria) this;
		}

		public Criteria andFilepathIsNotNull() {
			addCriterion("filepath is not null");
			return (Criteria) this;
		}

		public Criteria andFilepathEqualTo(String value) {
			addCriterion("filepath =", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotEqualTo(String value) {
			addCriterion("filepath <>", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathGreaterThan(String value) {
			addCriterion("filepath >", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathGreaterThanOrEqualTo(String value) {
			addCriterion("filepath >=", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathLessThan(String value) {
			addCriterion("filepath <", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathLessThanOrEqualTo(String value) {
			addCriterion("filepath <=", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathLike(String value) {
			addCriterion("filepath like", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotLike(String value) {
			addCriterion("filepath not like", value, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathIn(List<String> values) {
			addCriterion("filepath in", values, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotIn(List<String> values) {
			addCriterion("filepath not in", values, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathBetween(String value1, String value2) {
			addCriterion("filepath between", value1, value2, "filepath");
			return (Criteria) this;
		}

		public Criteria andFilepathNotBetween(String value1, String value2) {
			addCriterion("filepath not between", value1, value2, "filepath");
			return (Criteria) this;
		}

		public Criteria andUploadtimeIsNull() {
			addCriterion("uploadtime is null");
			return (Criteria) this;
		}

		public Criteria andUploadtimeIsNotNull() {
			addCriterion("uploadtime is not null");
			return (Criteria) this;
		}

		public Criteria andUploadtimeEqualTo(Integer value) {
			addCriterion("uploadtime =", value, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeNotEqualTo(Integer value) {
			addCriterion("uploadtime <>", value, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeGreaterThan(Integer value) {
			addCriterion("uploadtime >", value, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("uploadtime >=", value, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeLessThan(Integer value) {
			addCriterion("uploadtime <", value, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeLessThanOrEqualTo(Integer value) {
			addCriterion("uploadtime <=", value, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeIn(List<Integer> values) {
			addCriterion("uploadtime in", values, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeNotIn(List<Integer> values) {
			addCriterion("uploadtime not in", values, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeBetween(Integer value1, Integer value2) {
			addCriterion("uploadtime between", value1, value2, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andUploadtimeNotBetween(Integer value1, Integer value2) {
			addCriterion("uploadtime not between", value1, value2, "uploadtime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andSuffixIsNull() {
			addCriterion("suffix is null");
			return (Criteria) this;
		}

		public Criteria andSuffixIsNotNull() {
			addCriterion("suffix is not null");
			return (Criteria) this;
		}

		public Criteria andSuffixEqualTo(String value) {
			addCriterion("suffix =", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixNotEqualTo(String value) {
			addCriterion("suffix <>", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixGreaterThan(String value) {
			addCriterion("suffix >", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixGreaterThanOrEqualTo(String value) {
			addCriterion("suffix >=", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixLessThan(String value) {
			addCriterion("suffix <", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixLessThanOrEqualTo(String value) {
			addCriterion("suffix <=", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixLike(String value) {
			addCriterion("suffix like", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixNotLike(String value) {
			addCriterion("suffix not like", value, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixIn(List<String> values) {
			addCriterion("suffix in", values, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixNotIn(List<String> values) {
			addCriterion("suffix not in", values, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixBetween(String value1, String value2) {
			addCriterion("suffix between", value1, value2, "suffix");
			return (Criteria) this;
		}

		public Criteria andSuffixNotBetween(String value1, String value2) {
			addCriterion("suffix not between", value1, value2, "suffix");
			return (Criteria) this;
		}

		public Criteria andDownload_timesIsNull() {
			addCriterion("download_times is null");
			return (Criteria) this;
		}

		public Criteria andDownload_timesIsNotNull() {
			addCriterion("download_times is not null");
			return (Criteria) this;
		}

		public Criteria andDownload_timesEqualTo(Integer value) {
			addCriterion("download_times =", value, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesNotEqualTo(Integer value) {
			addCriterion("download_times <>", value, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesGreaterThan(Integer value) {
			addCriterion("download_times >", value, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesGreaterThanOrEqualTo(Integer value) {
			addCriterion("download_times >=", value, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesLessThan(Integer value) {
			addCriterion("download_times <", value, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesLessThanOrEqualTo(Integer value) {
			addCriterion("download_times <=", value, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesIn(List<Integer> values) {
			addCriterion("download_times in", values, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesNotIn(List<Integer> values) {
			addCriterion("download_times not in", values, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesBetween(Integer value1, Integer value2) {
			addCriterion("download_times between", value1, value2, "download_times");
			return (Criteria) this;
		}

		public Criteria andDownload_timesNotBetween(Integer value1, Integer value2) {
			addCriterion("download_times not between", value1, value2, "download_times");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNull() {
			addCriterion("store_id is null");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNotNull() {
			addCriterion("store_id is not null");
			return (Criteria) this;
		}

		public Criteria andStore_idEqualTo(Integer value) {
			addCriterion("store_id =", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotEqualTo(Integer value) {
			addCriterion("store_id <>", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThan(Integer value) {
			addCriterion("store_id >", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("store_id >=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThan(Integer value) {
			addCriterion("store_id <", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThanOrEqualTo(Integer value) {
			addCriterion("store_id <=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idIn(List<Integer> values) {
			addCriterion("store_id in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotIn(List<Integer> values) {
			addCriterion("store_id not in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idBetween(Integer value1, Integer value2) {
			addCriterion("store_id between", value1, value2, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotBetween(Integer value1, Integer value2) {
			addCriterion("store_id not between", value1, value2, "store_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cmf_asset
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cmf_asset
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 05 15:49:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}