package com.ehais.school_weixin.model;

import java.math.BigDecimal;

public class HaiAgency {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.agency_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short agency_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.agency_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String agency_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.legal_person
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String legal_person;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.linkman
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String linkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.tel
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.fax
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.email
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.longitude
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private BigDecimal longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.latitude
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private BigDecimal latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.void
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String col_void;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.logo
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.website
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.store_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer store_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.pinyin
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String pinyin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.country
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.province
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.city
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.county
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short county;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.district
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.street
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short street;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_agency.agency_desc
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String agency_desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.agency_id
	 * @return  the value of hai_agency.agency_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getAgency_id() {
		return agency_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.agency_id
	 * @param agency_id  the value for hai_agency.agency_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setAgency_id(Short agency_id) {
		this.agency_id = agency_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.agency_name
	 * @return  the value of hai_agency.agency_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getAgency_name() {
		return agency_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.agency_name
	 * @param agency_name  the value for hai_agency.agency_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setAgency_name(String agency_name) {
		this.agency_name = agency_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.legal_person
	 * @return  the value of hai_agency.legal_person
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getLegal_person() {
		return legal_person;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.legal_person
	 * @param legal_person  the value for hai_agency.legal_person
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLegal_person(String legal_person) {
		this.legal_person = legal_person;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.linkman
	 * @return  the value of hai_agency.linkman
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.linkman
	 * @param linkman  the value for hai_agency.linkman
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.tel
	 * @return  the value of hai_agency.tel
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.tel
	 * @param tel  the value for hai_agency.tel
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.fax
	 * @return  the value of hai_agency.fax
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.fax
	 * @param fax  the value for hai_agency.fax
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.email
	 * @return  the value of hai_agency.email
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.email
	 * @param email  the value for hai_agency.email
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.address
	 * @return  the value of hai_agency.address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.address
	 * @param address  the value for hai_agency.address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.longitude
	 * @return  the value of hai_agency.longitude
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.longitude
	 * @param longitude  the value for hai_agency.longitude
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.latitude
	 * @return  the value of hai_agency.latitude
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.latitude
	 * @param latitude  the value for hai_agency.latitude
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.void
	 * @return  the value of hai_agency.void
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getCol_void() {
		return col_void;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.void
	 * @param col_void  the value for hai_agency.void
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCol_void(String col_void) {
		this.col_void = col_void;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.logo
	 * @return  the value of hai_agency.logo
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.logo
	 * @param logo  the value for hai_agency.logo
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLogo(String logo) {
		this.logo = logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.website
	 * @return  the value of hai_agency.website
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.website
	 * @param website  the value for hai_agency.website
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.store_id
	 * @return  the value of hai_agency.store_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getStore_id() {
		return store_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.store_id
	 * @param store_id  the value for hai_agency.store_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setStore_id(Integer store_id) {
		this.store_id = store_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.pinyin
	 * @return  the value of hai_agency.pinyin
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getPinyin() {
		return pinyin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.pinyin
	 * @param pinyin  the value for hai_agency.pinyin
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.country
	 * @return  the value of hai_agency.country
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.country
	 * @param country  the value for hai_agency.country
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCountry(Short country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.province
	 * @return  the value of hai_agency.province
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.province
	 * @param province  the value for hai_agency.province
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setProvince(Short province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.city
	 * @return  the value of hai_agency.city
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.city
	 * @param city  the value for hai_agency.city
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCity(Short city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.county
	 * @return  the value of hai_agency.county
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.county
	 * @param county  the value for hai_agency.county
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCounty(Short county) {
		this.county = county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.district
	 * @return  the value of hai_agency.district
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.district
	 * @param district  the value for hai_agency.district
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistrict(Short district) {
		this.district = district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.street
	 * @return  the value of hai_agency.street
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getStreet() {
		return street;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.street
	 * @param street  the value for hai_agency.street
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setStreet(Short street) {
		this.street = street;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_agency.agency_desc
	 * @return  the value of hai_agency.agency_desc
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getAgency_desc() {
		return agency_desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_agency.agency_desc
	 * @param agency_desc  the value for hai_agency.agency_desc
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setAgency_desc(String agency_desc) {
		this.agency_desc = agency_desc;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_agency.void
     *
     * @mbg.generated Mon Dec 05 15:49:06 CST 2016
     */
    //private String void;

    
}