package com.ehais.school_weixin.model;

public class HaiAdminLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_admin_log.log_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer log_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_admin_log.log_time
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer log_time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_admin_log.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Byte user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_admin_log.log_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String log_info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_admin_log.ip_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String ip_address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_admin_log.log_id
	 * @return  the value of hai_admin_log.log_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getLog_id() {
		return log_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_admin_log.log_id
	 * @param log_id  the value for hai_admin_log.log_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLog_id(Integer log_id) {
		this.log_id = log_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_admin_log.log_time
	 * @return  the value of hai_admin_log.log_time
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getLog_time() {
		return log_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_admin_log.log_time
	 * @param log_time  the value for hai_admin_log.log_time
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLog_time(Integer log_time) {
		this.log_time = log_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_admin_log.user_id
	 * @return  the value of hai_admin_log.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Byte getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_admin_log.user_id
	 * @param user_id  the value for hai_admin_log.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setUser_id(Byte user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_admin_log.log_info
	 * @return  the value of hai_admin_log.log_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getLog_info() {
		return log_info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_admin_log.log_info
	 * @param log_info  the value for hai_admin_log.log_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLog_info(String log_info) {
		this.log_info = log_info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_admin_log.ip_address
	 * @return  the value of hai_admin_log.ip_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getIp_address() {
		return ip_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_admin_log.ip_address
	 * @param ip_address  the value for hai_admin_log.ip_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setIp_address(String ip_address) {
		this.ip_address = ip_address;
	}
}