package com.ehais.school_weixin.model;

import java.util.ArrayList;
import java.util.List;

public class HaiAdminUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public HaiAdminUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAdmin_idIsNull() {
			addCriterion("admin_id is null");
			return (Criteria) this;
		}

		public Criteria andAdmin_idIsNotNull() {
			addCriterion("admin_id is not null");
			return (Criteria) this;
		}

		public Criteria andAdmin_idEqualTo(Short value) {
			addCriterion("admin_id =", value, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idNotEqualTo(Short value) {
			addCriterion("admin_id <>", value, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idGreaterThan(Short value) {
			addCriterion("admin_id >", value, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idGreaterThanOrEqualTo(Short value) {
			addCriterion("admin_id >=", value, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idLessThan(Short value) {
			addCriterion("admin_id <", value, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idLessThanOrEqualTo(Short value) {
			addCriterion("admin_id <=", value, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idIn(List<Short> values) {
			addCriterion("admin_id in", values, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idNotIn(List<Short> values) {
			addCriterion("admin_id not in", values, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idBetween(Short value1, Short value2) {
			addCriterion("admin_id between", value1, value2, "admin_id");
			return (Criteria) this;
		}

		public Criteria andAdmin_idNotBetween(Short value1, Short value2) {
			addCriterion("admin_id not between", value1, value2, "admin_id");
			return (Criteria) this;
		}

		public Criteria andUser_nameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUser_nameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUser_nameEqualTo(String value) {
			addCriterion("user_name =", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameGreaterThan(String value) {
			addCriterion("user_name >", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLessThan(String value) {
			addCriterion("user_name <", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameLike(String value) {
			addCriterion("user_name like", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotLike(String value) {
			addCriterion("user_name not like", value, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameIn(List<String> values) {
			addCriterion("user_name in", values, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "user_name");
			return (Criteria) this;
		}

		public Criteria andUser_nameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "user_name");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andEc_saltIsNull() {
			addCriterion("ec_salt is null");
			return (Criteria) this;
		}

		public Criteria andEc_saltIsNotNull() {
			addCriterion("ec_salt is not null");
			return (Criteria) this;
		}

		public Criteria andEc_saltEqualTo(String value) {
			addCriterion("ec_salt =", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltNotEqualTo(String value) {
			addCriterion("ec_salt <>", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltGreaterThan(String value) {
			addCriterion("ec_salt >", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltGreaterThanOrEqualTo(String value) {
			addCriterion("ec_salt >=", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltLessThan(String value) {
			addCriterion("ec_salt <", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltLessThanOrEqualTo(String value) {
			addCriterion("ec_salt <=", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltLike(String value) {
			addCriterion("ec_salt like", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltNotLike(String value) {
			addCriterion("ec_salt not like", value, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltIn(List<String> values) {
			addCriterion("ec_salt in", values, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltNotIn(List<String> values) {
			addCriterion("ec_salt not in", values, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltBetween(String value1, String value2) {
			addCriterion("ec_salt between", value1, value2, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andEc_saltNotBetween(String value1, String value2) {
			addCriterion("ec_salt not between", value1, value2, "ec_salt");
			return (Criteria) this;
		}

		public Criteria andAdd_timeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAdd_timeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAdd_timeEqualTo(Integer value) {
			addCriterion("add_time =", value, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeNotEqualTo(Integer value) {
			addCriterion("add_time <>", value, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeGreaterThan(Integer value) {
			addCriterion("add_time >", value, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeGreaterThanOrEqualTo(Integer value) {
			addCriterion("add_time >=", value, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeLessThan(Integer value) {
			addCriterion("add_time <", value, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeLessThanOrEqualTo(Integer value) {
			addCriterion("add_time <=", value, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeIn(List<Integer> values) {
			addCriterion("add_time in", values, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeNotIn(List<Integer> values) {
			addCriterion("add_time not in", values, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeBetween(Integer value1, Integer value2) {
			addCriterion("add_time between", value1, value2, "add_time");
			return (Criteria) this;
		}

		public Criteria andAdd_timeNotBetween(Integer value1, Integer value2) {
			addCriterion("add_time not between", value1, value2, "add_time");
			return (Criteria) this;
		}

		public Criteria andLast_loginIsNull() {
			addCriterion("last_login is null");
			return (Criteria) this;
		}

		public Criteria andLast_loginIsNotNull() {
			addCriterion("last_login is not null");
			return (Criteria) this;
		}

		public Criteria andLast_loginEqualTo(Integer value) {
			addCriterion("last_login =", value, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginNotEqualTo(Integer value) {
			addCriterion("last_login <>", value, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginGreaterThan(Integer value) {
			addCriterion("last_login >", value, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginGreaterThanOrEqualTo(Integer value) {
			addCriterion("last_login >=", value, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginLessThan(Integer value) {
			addCriterion("last_login <", value, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginLessThanOrEqualTo(Integer value) {
			addCriterion("last_login <=", value, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginIn(List<Integer> values) {
			addCriterion("last_login in", values, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginNotIn(List<Integer> values) {
			addCriterion("last_login not in", values, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginBetween(Integer value1, Integer value2) {
			addCriterion("last_login between", value1, value2, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_loginNotBetween(Integer value1, Integer value2) {
			addCriterion("last_login not between", value1, value2, "last_login");
			return (Criteria) this;
		}

		public Criteria andLast_ipIsNull() {
			addCriterion("last_ip is null");
			return (Criteria) this;
		}

		public Criteria andLast_ipIsNotNull() {
			addCriterion("last_ip is not null");
			return (Criteria) this;
		}

		public Criteria andLast_ipEqualTo(String value) {
			addCriterion("last_ip =", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipNotEqualTo(String value) {
			addCriterion("last_ip <>", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipGreaterThan(String value) {
			addCriterion("last_ip >", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipGreaterThanOrEqualTo(String value) {
			addCriterion("last_ip >=", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipLessThan(String value) {
			addCriterion("last_ip <", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipLessThanOrEqualTo(String value) {
			addCriterion("last_ip <=", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipLike(String value) {
			addCriterion("last_ip like", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipNotLike(String value) {
			addCriterion("last_ip not like", value, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipIn(List<String> values) {
			addCriterion("last_ip in", values, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipNotIn(List<String> values) {
			addCriterion("last_ip not in", values, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipBetween(String value1, String value2) {
			addCriterion("last_ip between", value1, value2, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLast_ipNotBetween(String value1, String value2) {
			addCriterion("last_ip not between", value1, value2, "last_ip");
			return (Criteria) this;
		}

		public Criteria andLang_typeIsNull() {
			addCriterion("lang_type is null");
			return (Criteria) this;
		}

		public Criteria andLang_typeIsNotNull() {
			addCriterion("lang_type is not null");
			return (Criteria) this;
		}

		public Criteria andLang_typeEqualTo(String value) {
			addCriterion("lang_type =", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeNotEqualTo(String value) {
			addCriterion("lang_type <>", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeGreaterThan(String value) {
			addCriterion("lang_type >", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeGreaterThanOrEqualTo(String value) {
			addCriterion("lang_type >=", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeLessThan(String value) {
			addCriterion("lang_type <", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeLessThanOrEqualTo(String value) {
			addCriterion("lang_type <=", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeLike(String value) {
			addCriterion("lang_type like", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeNotLike(String value) {
			addCriterion("lang_type not like", value, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeIn(List<String> values) {
			addCriterion("lang_type in", values, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeNotIn(List<String> values) {
			addCriterion("lang_type not in", values, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeBetween(String value1, String value2) {
			addCriterion("lang_type between", value1, value2, "lang_type");
			return (Criteria) this;
		}

		public Criteria andLang_typeNotBetween(String value1, String value2) {
			addCriterion("lang_type not between", value1, value2, "lang_type");
			return (Criteria) this;
		}

		public Criteria andAgency_idIsNull() {
			addCriterion("agency_id is null");
			return (Criteria) this;
		}

		public Criteria andAgency_idIsNotNull() {
			addCriterion("agency_id is not null");
			return (Criteria) this;
		}

		public Criteria andAgency_idEqualTo(Short value) {
			addCriterion("agency_id =", value, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idNotEqualTo(Short value) {
			addCriterion("agency_id <>", value, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idGreaterThan(Short value) {
			addCriterion("agency_id >", value, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idGreaterThanOrEqualTo(Short value) {
			addCriterion("agency_id >=", value, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idLessThan(Short value) {
			addCriterion("agency_id <", value, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idLessThanOrEqualTo(Short value) {
			addCriterion("agency_id <=", value, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idIn(List<Short> values) {
			addCriterion("agency_id in", values, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idNotIn(List<Short> values) {
			addCriterion("agency_id not in", values, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idBetween(Short value1, Short value2) {
			addCriterion("agency_id between", value1, value2, "agency_id");
			return (Criteria) this;
		}

		public Criteria andAgency_idNotBetween(Short value1, Short value2) {
			addCriterion("agency_id not between", value1, value2, "agency_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idIsNull() {
			addCriterion("business_id is null");
			return (Criteria) this;
		}

		public Criteria andBusiness_idIsNotNull() {
			addCriterion("business_id is not null");
			return (Criteria) this;
		}

		public Criteria andBusiness_idEqualTo(Short value) {
			addCriterion("business_id =", value, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idNotEqualTo(Short value) {
			addCriterion("business_id <>", value, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idGreaterThan(Short value) {
			addCriterion("business_id >", value, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idGreaterThanOrEqualTo(Short value) {
			addCriterion("business_id >=", value, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idLessThan(Short value) {
			addCriterion("business_id <", value, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idLessThanOrEqualTo(Short value) {
			addCriterion("business_id <=", value, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idIn(List<Short> values) {
			addCriterion("business_id in", values, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idNotIn(List<Short> values) {
			addCriterion("business_id not in", values, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idBetween(Short value1, Short value2) {
			addCriterion("business_id between", value1, value2, "business_id");
			return (Criteria) this;
		}

		public Criteria andBusiness_idNotBetween(Short value1, Short value2) {
			addCriterion("business_id not between", value1, value2, "business_id");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNull() {
			addCriterion("store_id is null");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNotNull() {
			addCriterion("store_id is not null");
			return (Criteria) this;
		}

		public Criteria andStore_idEqualTo(Integer value) {
			addCriterion("store_id =", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotEqualTo(Integer value) {
			addCriterion("store_id <>", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThan(Integer value) {
			addCriterion("store_id >", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("store_id >=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThan(Integer value) {
			addCriterion("store_id <", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThanOrEqualTo(Integer value) {
			addCriterion("store_id <=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idIn(List<Integer> values) {
			addCriterion("store_id in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotIn(List<Integer> values) {
			addCriterion("store_id not in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idBetween(Integer value1, Integer value2) {
			addCriterion("store_id between", value1, value2, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotBetween(Integer value1, Integer value2) {
			addCriterion("store_id not between", value1, value2, "store_id");
			return (Criteria) this;
		}

		public Criteria andProject_folderIsNull() {
			addCriterion("project_folder is null");
			return (Criteria) this;
		}

		public Criteria andProject_folderIsNotNull() {
			addCriterion("project_folder is not null");
			return (Criteria) this;
		}

		public Criteria andProject_folderEqualTo(String value) {
			addCriterion("project_folder =", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderNotEqualTo(String value) {
			addCriterion("project_folder <>", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderGreaterThan(String value) {
			addCriterion("project_folder >", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderGreaterThanOrEqualTo(String value) {
			addCriterion("project_folder >=", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderLessThan(String value) {
			addCriterion("project_folder <", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderLessThanOrEqualTo(String value) {
			addCriterion("project_folder <=", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderLike(String value) {
			addCriterion("project_folder like", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderNotLike(String value) {
			addCriterion("project_folder not like", value, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderIn(List<String> values) {
			addCriterion("project_folder in", values, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderNotIn(List<String> values) {
			addCriterion("project_folder not in", values, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderBetween(String value1, String value2) {
			addCriterion("project_folder between", value1, value2, "project_folder");
			return (Criteria) this;
		}

		public Criteria andProject_folderNotBetween(String value1, String value2) {
			addCriterion("project_folder not between", value1, value2, "project_folder");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_admin_user
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_admin_user
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 05 15:49:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}