package com.ehais.school_weixin.model;

import java.util.ArrayList;
import java.util.List;

public class HaiChapterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public HaiChapterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCha_idIsNull() {
			addCriterion("cha_id is null");
			return (Criteria) this;
		}

		public Criteria andCha_idIsNotNull() {
			addCriterion("cha_id is not null");
			return (Criteria) this;
		}

		public Criteria andCha_idEqualTo(Integer value) {
			addCriterion("cha_id =", value, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idNotEqualTo(Integer value) {
			addCriterion("cha_id <>", value, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idGreaterThan(Integer value) {
			addCriterion("cha_id >", value, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("cha_id >=", value, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idLessThan(Integer value) {
			addCriterion("cha_id <", value, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idLessThanOrEqualTo(Integer value) {
			addCriterion("cha_id <=", value, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idIn(List<Integer> values) {
			addCriterion("cha_id in", values, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idNotIn(List<Integer> values) {
			addCriterion("cha_id not in", values, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idBetween(Integer value1, Integer value2) {
			addCriterion("cha_id between", value1, value2, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_idNotBetween(Integer value1, Integer value2) {
			addCriterion("cha_id not between", value1, value2, "cha_id");
			return (Criteria) this;
		}

		public Criteria andCha_nameIsNull() {
			addCriterion("cha_name is null");
			return (Criteria) this;
		}

		public Criteria andCha_nameIsNotNull() {
			addCriterion("cha_name is not null");
			return (Criteria) this;
		}

		public Criteria andCha_nameEqualTo(String value) {
			addCriterion("cha_name =", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameNotEqualTo(String value) {
			addCriterion("cha_name <>", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameGreaterThan(String value) {
			addCriterion("cha_name >", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameGreaterThanOrEqualTo(String value) {
			addCriterion("cha_name >=", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameLessThan(String value) {
			addCriterion("cha_name <", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameLessThanOrEqualTo(String value) {
			addCriterion("cha_name <=", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameLike(String value) {
			addCriterion("cha_name like", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameNotLike(String value) {
			addCriterion("cha_name not like", value, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameIn(List<String> values) {
			addCriterion("cha_name in", values, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameNotIn(List<String> values) {
			addCriterion("cha_name not in", values, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameBetween(String value1, String value2) {
			addCriterion("cha_name between", value1, value2, "cha_name");
			return (Criteria) this;
		}

		public Criteria andCha_nameNotBetween(String value1, String value2) {
			addCriterion("cha_name not between", value1, value2, "cha_name");
			return (Criteria) this;
		}

		public Criteria andGoods_idIsNull() {
			addCriterion("goods_id is null");
			return (Criteria) this;
		}

		public Criteria andGoods_idIsNotNull() {
			addCriterion("goods_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoods_idEqualTo(Integer value) {
			addCriterion("goods_id =", value, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idNotEqualTo(Integer value) {
			addCriterion("goods_id <>", value, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idGreaterThan(Integer value) {
			addCriterion("goods_id >", value, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("goods_id >=", value, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idLessThan(Integer value) {
			addCriterion("goods_id <", value, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idLessThanOrEqualTo(Integer value) {
			addCriterion("goods_id <=", value, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idIn(List<Integer> values) {
			addCriterion("goods_id in", values, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idNotIn(List<Integer> values) {
			addCriterion("goods_id not in", values, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idBetween(Integer value1, Integer value2) {
			addCriterion("goods_id between", value1, value2, "goods_id");
			return (Criteria) this;
		}

		public Criteria andGoods_idNotBetween(Integer value1, Integer value2) {
			addCriterion("goods_id not between", value1, value2, "goods_id");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNull() {
			addCriterion("store_id is null");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNotNull() {
			addCriterion("store_id is not null");
			return (Criteria) this;
		}

		public Criteria andStore_idEqualTo(Integer value) {
			addCriterion("store_id =", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotEqualTo(Integer value) {
			addCriterion("store_id <>", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThan(Integer value) {
			addCriterion("store_id >", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("store_id >=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThan(Integer value) {
			addCriterion("store_id <", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThanOrEqualTo(Integer value) {
			addCriterion("store_id <=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idIn(List<Integer> values) {
			addCriterion("store_id in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotIn(List<Integer> values) {
			addCriterion("store_id not in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idBetween(Integer value1, Integer value2) {
			addCriterion("store_id between", value1, value2, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotBetween(Integer value1, Integer value2) {
			addCriterion("store_id not between", value1, value2, "store_id");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_chapter
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_chapter
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 05 15:49:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}