package com.ehais.school_weixin.model;

public class HaiCatRecommendKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_cat_recommend.cat_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short cat_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_cat_recommend.recommend_type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Boolean recommend_type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_cat_recommend.cat_id
	 * @return  the value of hai_cat_recommend.cat_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getCat_id() {
		return cat_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_cat_recommend.cat_id
	 * @param cat_id  the value for hai_cat_recommend.cat_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCat_id(Short cat_id) {
		this.cat_id = cat_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_cat_recommend.recommend_type
	 * @return  the value of hai_cat_recommend.recommend_type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Boolean getRecommend_type() {
		return recommend_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_cat_recommend.recommend_type
	 * @param recommend_type  the value for hai_cat_recommend.recommend_type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setRecommend_type(Boolean recommend_type) {
		this.recommend_type = recommend_type;
	}
}