package com.ehais.school_weixin.model;

import java.util.ArrayList;
import java.util.List;

public class HaiCategoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public HaiCategoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCat_idIsNull() {
			addCriterion("cat_id is null");
			return (Criteria) this;
		}

		public Criteria andCat_idIsNotNull() {
			addCriterion("cat_id is not null");
			return (Criteria) this;
		}

		public Criteria andCat_idEqualTo(Integer value) {
			addCriterion("cat_id =", value, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idNotEqualTo(Integer value) {
			addCriterion("cat_id <>", value, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idGreaterThan(Integer value) {
			addCriterion("cat_id >", value, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("cat_id >=", value, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idLessThan(Integer value) {
			addCriterion("cat_id <", value, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idLessThanOrEqualTo(Integer value) {
			addCriterion("cat_id <=", value, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idIn(List<Integer> values) {
			addCriterion("cat_id in", values, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idNotIn(List<Integer> values) {
			addCriterion("cat_id not in", values, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idBetween(Integer value1, Integer value2) {
			addCriterion("cat_id between", value1, value2, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_idNotBetween(Integer value1, Integer value2) {
			addCriterion("cat_id not between", value1, value2, "cat_id");
			return (Criteria) this;
		}

		public Criteria andCat_nameIsNull() {
			addCriterion("cat_name is null");
			return (Criteria) this;
		}

		public Criteria andCat_nameIsNotNull() {
			addCriterion("cat_name is not null");
			return (Criteria) this;
		}

		public Criteria andCat_nameEqualTo(String value) {
			addCriterion("cat_name =", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameNotEqualTo(String value) {
			addCriterion("cat_name <>", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameGreaterThan(String value) {
			addCriterion("cat_name >", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameGreaterThanOrEqualTo(String value) {
			addCriterion("cat_name >=", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameLessThan(String value) {
			addCriterion("cat_name <", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameLessThanOrEqualTo(String value) {
			addCriterion("cat_name <=", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameLike(String value) {
			addCriterion("cat_name like", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameNotLike(String value) {
			addCriterion("cat_name not like", value, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameIn(List<String> values) {
			addCriterion("cat_name in", values, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameNotIn(List<String> values) {
			addCriterion("cat_name not in", values, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameBetween(String value1, String value2) {
			addCriterion("cat_name between", value1, value2, "cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_nameNotBetween(String value1, String value2) {
			addCriterion("cat_name not between", value1, value2, "cat_name");
			return (Criteria) this;
		}

		public Criteria andKeywordsIsNull() {
			addCriterion("keywords is null");
			return (Criteria) this;
		}

		public Criteria andKeywordsIsNotNull() {
			addCriterion("keywords is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordsEqualTo(String value) {
			addCriterion("keywords =", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotEqualTo(String value) {
			addCriterion("keywords <>", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsGreaterThan(String value) {
			addCriterion("keywords >", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
			addCriterion("keywords >=", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsLessThan(String value) {
			addCriterion("keywords <", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsLessThanOrEqualTo(String value) {
			addCriterion("keywords <=", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsLike(String value) {
			addCriterion("keywords like", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotLike(String value) {
			addCriterion("keywords not like", value, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsIn(List<String> values) {
			addCriterion("keywords in", values, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotIn(List<String> values) {
			addCriterion("keywords not in", values, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsBetween(String value1, String value2) {
			addCriterion("keywords between", value1, value2, "keywords");
			return (Criteria) this;
		}

		public Criteria andKeywordsNotBetween(String value1, String value2) {
			addCriterion("keywords not between", value1, value2, "keywords");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameIsNull() {
			addCriterion("sub_cat_name is null");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameIsNotNull() {
			addCriterion("sub_cat_name is not null");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameEqualTo(String value) {
			addCriterion("sub_cat_name =", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameNotEqualTo(String value) {
			addCriterion("sub_cat_name <>", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameGreaterThan(String value) {
			addCriterion("sub_cat_name >", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameGreaterThanOrEqualTo(String value) {
			addCriterion("sub_cat_name >=", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameLessThan(String value) {
			addCriterion("sub_cat_name <", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameLessThanOrEqualTo(String value) {
			addCriterion("sub_cat_name <=", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameLike(String value) {
			addCriterion("sub_cat_name like", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameNotLike(String value) {
			addCriterion("sub_cat_name not like", value, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameIn(List<String> values) {
			addCriterion("sub_cat_name in", values, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameNotIn(List<String> values) {
			addCriterion("sub_cat_name not in", values, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameBetween(String value1, String value2) {
			addCriterion("sub_cat_name between", value1, value2, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andSub_cat_nameNotBetween(String value1, String value2) {
			addCriterion("sub_cat_name not between", value1, value2, "sub_cat_name");
			return (Criteria) this;
		}

		public Criteria andCat_descIsNull() {
			addCriterion("cat_desc is null");
			return (Criteria) this;
		}

		public Criteria andCat_descIsNotNull() {
			addCriterion("cat_desc is not null");
			return (Criteria) this;
		}

		public Criteria andCat_descEqualTo(String value) {
			addCriterion("cat_desc =", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descNotEqualTo(String value) {
			addCriterion("cat_desc <>", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descGreaterThan(String value) {
			addCriterion("cat_desc >", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descGreaterThanOrEqualTo(String value) {
			addCriterion("cat_desc >=", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descLessThan(String value) {
			addCriterion("cat_desc <", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descLessThanOrEqualTo(String value) {
			addCriterion("cat_desc <=", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descLike(String value) {
			addCriterion("cat_desc like", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descNotLike(String value) {
			addCriterion("cat_desc not like", value, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descIn(List<String> values) {
			addCriterion("cat_desc in", values, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descNotIn(List<String> values) {
			addCriterion("cat_desc not in", values, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descBetween(String value1, String value2) {
			addCriterion("cat_desc between", value1, value2, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andCat_descNotBetween(String value1, String value2) {
			addCriterion("cat_desc not between", value1, value2, "cat_desc");
			return (Criteria) this;
		}

		public Criteria andParent_idIsNull() {
			addCriterion("parent_id is null");
			return (Criteria) this;
		}

		public Criteria andParent_idIsNotNull() {
			addCriterion("parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andParent_idEqualTo(Integer value) {
			addCriterion("parent_id =", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idNotEqualTo(Integer value) {
			addCriterion("parent_id <>", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idGreaterThan(Integer value) {
			addCriterion("parent_id >", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("parent_id >=", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idLessThan(Integer value) {
			addCriterion("parent_id <", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idLessThanOrEqualTo(Integer value) {
			addCriterion("parent_id <=", value, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idIn(List<Integer> values) {
			addCriterion("parent_id in", values, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idNotIn(List<Integer> values) {
			addCriterion("parent_id not in", values, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idBetween(Integer value1, Integer value2) {
			addCriterion("parent_id between", value1, value2, "parent_id");
			return (Criteria) this;
		}

		public Criteria andParent_idNotBetween(Integer value1, Integer value2) {
			addCriterion("parent_id not between", value1, value2, "parent_id");
			return (Criteria) this;
		}

		public Criteria andSort_orderIsNull() {
			addCriterion("sort_order is null");
			return (Criteria) this;
		}

		public Criteria andSort_orderIsNotNull() {
			addCriterion("sort_order is not null");
			return (Criteria) this;
		}

		public Criteria andSort_orderEqualTo(Short value) {
			addCriterion("sort_order =", value, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderNotEqualTo(Short value) {
			addCriterion("sort_order <>", value, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderGreaterThan(Short value) {
			addCriterion("sort_order >", value, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderGreaterThanOrEqualTo(Short value) {
			addCriterion("sort_order >=", value, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderLessThan(Short value) {
			addCriterion("sort_order <", value, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderLessThanOrEqualTo(Short value) {
			addCriterion("sort_order <=", value, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderIn(List<Short> values) {
			addCriterion("sort_order in", values, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderNotIn(List<Short> values) {
			addCriterion("sort_order not in", values, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderBetween(Short value1, Short value2) {
			addCriterion("sort_order between", value1, value2, "sort_order");
			return (Criteria) this;
		}

		public Criteria andSort_orderNotBetween(Short value1, Short value2) {
			addCriterion("sort_order not between", value1, value2, "sort_order");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileIsNull() {
			addCriterion("template_file is null");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileIsNotNull() {
			addCriterion("template_file is not null");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileEqualTo(String value) {
			addCriterion("template_file =", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileNotEqualTo(String value) {
			addCriterion("template_file <>", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileGreaterThan(String value) {
			addCriterion("template_file >", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileGreaterThanOrEqualTo(String value) {
			addCriterion("template_file >=", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileLessThan(String value) {
			addCriterion("template_file <", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileLessThanOrEqualTo(String value) {
			addCriterion("template_file <=", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileLike(String value) {
			addCriterion("template_file like", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileNotLike(String value) {
			addCriterion("template_file not like", value, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileIn(List<String> values) {
			addCriterion("template_file in", values, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileNotIn(List<String> values) {
			addCriterion("template_file not in", values, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileBetween(String value1, String value2) {
			addCriterion("template_file between", value1, value2, "template_file");
			return (Criteria) this;
		}

		public Criteria andTemplate_fileNotBetween(String value1, String value2) {
			addCriterion("template_file not between", value1, value2, "template_file");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitIsNull() {
			addCriterion("measure_unit is null");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitIsNotNull() {
			addCriterion("measure_unit is not null");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitEqualTo(String value) {
			addCriterion("measure_unit =", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitNotEqualTo(String value) {
			addCriterion("measure_unit <>", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitGreaterThan(String value) {
			addCriterion("measure_unit >", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitGreaterThanOrEqualTo(String value) {
			addCriterion("measure_unit >=", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitLessThan(String value) {
			addCriterion("measure_unit <", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitLessThanOrEqualTo(String value) {
			addCriterion("measure_unit <=", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitLike(String value) {
			addCriterion("measure_unit like", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitNotLike(String value) {
			addCriterion("measure_unit not like", value, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitIn(List<String> values) {
			addCriterion("measure_unit in", values, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitNotIn(List<String> values) {
			addCriterion("measure_unit not in", values, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitBetween(String value1, String value2) {
			addCriterion("measure_unit between", value1, value2, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andMeasure_unitNotBetween(String value1, String value2) {
			addCriterion("measure_unit not between", value1, value2, "measure_unit");
			return (Criteria) this;
		}

		public Criteria andShow_in_navIsNull() {
			addCriterion("show_in_nav is null");
			return (Criteria) this;
		}

		public Criteria andShow_in_navIsNotNull() {
			addCriterion("show_in_nav is not null");
			return (Criteria) this;
		}

		public Criteria andShow_in_navEqualTo(Boolean value) {
			addCriterion("show_in_nav =", value, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navNotEqualTo(Boolean value) {
			addCriterion("show_in_nav <>", value, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navGreaterThan(Boolean value) {
			addCriterion("show_in_nav >", value, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navGreaterThanOrEqualTo(Boolean value) {
			addCriterion("show_in_nav >=", value, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navLessThan(Boolean value) {
			addCriterion("show_in_nav <", value, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navLessThanOrEqualTo(Boolean value) {
			addCriterion("show_in_nav <=", value, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navIn(List<Boolean> values) {
			addCriterion("show_in_nav in", values, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navNotIn(List<Boolean> values) {
			addCriterion("show_in_nav not in", values, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navBetween(Boolean value1, Boolean value2) {
			addCriterion("show_in_nav between", value1, value2, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andShow_in_navNotBetween(Boolean value1, Boolean value2) {
			addCriterion("show_in_nav not between", value1, value2, "show_in_nav");
			return (Criteria) this;
		}

		public Criteria andStyleIsNull() {
			addCriterion("style is null");
			return (Criteria) this;
		}

		public Criteria andStyleIsNotNull() {
			addCriterion("style is not null");
			return (Criteria) this;
		}

		public Criteria andStyleEqualTo(String value) {
			addCriterion("style =", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotEqualTo(String value) {
			addCriterion("style <>", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleGreaterThan(String value) {
			addCriterion("style >", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleGreaterThanOrEqualTo(String value) {
			addCriterion("style >=", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLessThan(String value) {
			addCriterion("style <", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLessThanOrEqualTo(String value) {
			addCriterion("style <=", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleLike(String value) {
			addCriterion("style like", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotLike(String value) {
			addCriterion("style not like", value, "style");
			return (Criteria) this;
		}

		public Criteria andStyleIn(List<String> values) {
			addCriterion("style in", values, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotIn(List<String> values) {
			addCriterion("style not in", values, "style");
			return (Criteria) this;
		}

		public Criteria andStyleBetween(String value1, String value2) {
			addCriterion("style between", value1, value2, "style");
			return (Criteria) this;
		}

		public Criteria andStyleNotBetween(String value1, String value2) {
			addCriterion("style not between", value1, value2, "style");
			return (Criteria) this;
		}

		public Criteria andIs_showIsNull() {
			addCriterion("is_show is null");
			return (Criteria) this;
		}

		public Criteria andIs_showIsNotNull() {
			addCriterion("is_show is not null");
			return (Criteria) this;
		}

		public Criteria andIs_showEqualTo(Boolean value) {
			addCriterion("is_show =", value, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showNotEqualTo(Boolean value) {
			addCriterion("is_show <>", value, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showGreaterThan(Boolean value) {
			addCriterion("is_show >", value, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_show >=", value, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showLessThan(Boolean value) {
			addCriterion("is_show <", value, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showLessThanOrEqualTo(Boolean value) {
			addCriterion("is_show <=", value, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showIn(List<Boolean> values) {
			addCriterion("is_show in", values, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showNotIn(List<Boolean> values) {
			addCriterion("is_show not in", values, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showBetween(Boolean value1, Boolean value2) {
			addCriterion("is_show between", value1, value2, "is_show");
			return (Criteria) this;
		}

		public Criteria andIs_showNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_show not between", value1, value2, "is_show");
			return (Criteria) this;
		}

		public Criteria andGradeIsNull() {
			addCriterion("grade is null");
			return (Criteria) this;
		}

		public Criteria andGradeIsNotNull() {
			addCriterion("grade is not null");
			return (Criteria) this;
		}

		public Criteria andGradeEqualTo(Short value) {
			addCriterion("grade =", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeNotEqualTo(Short value) {
			addCriterion("grade <>", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeGreaterThan(Short value) {
			addCriterion("grade >", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeGreaterThanOrEqualTo(Short value) {
			addCriterion("grade >=", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeLessThan(Short value) {
			addCriterion("grade <", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeLessThanOrEqualTo(Short value) {
			addCriterion("grade <=", value, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeIn(List<Short> values) {
			addCriterion("grade in", values, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeNotIn(List<Short> values) {
			addCriterion("grade not in", values, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeBetween(Short value1, Short value2) {
			addCriterion("grade between", value1, value2, "grade");
			return (Criteria) this;
		}

		public Criteria andGradeNotBetween(Short value1, Short value2) {
			addCriterion("grade not between", value1, value2, "grade");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNull() {
			addCriterion("store_id is null");
			return (Criteria) this;
		}

		public Criteria andStore_idIsNotNull() {
			addCriterion("store_id is not null");
			return (Criteria) this;
		}

		public Criteria andStore_idEqualTo(Integer value) {
			addCriterion("store_id =", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotEqualTo(Integer value) {
			addCriterion("store_id <>", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThan(Integer value) {
			addCriterion("store_id >", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("store_id >=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThan(Integer value) {
			addCriterion("store_id <", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idLessThanOrEqualTo(Integer value) {
			addCriterion("store_id <=", value, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idIn(List<Integer> values) {
			addCriterion("store_id in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotIn(List<Integer> values) {
			addCriterion("store_id not in", values, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idBetween(Integer value1, Integer value2) {
			addCriterion("store_id between", value1, value2, "store_id");
			return (Criteria) this;
		}

		public Criteria andStore_idNotBetween(Integer value1, Integer value2) {
			addCriterion("store_id not between", value1, value2, "store_id");
			return (Criteria) this;
		}

		public Criteria andThumbIsNull() {
			addCriterion("thumb is null");
			return (Criteria) this;
		}

		public Criteria andThumbIsNotNull() {
			addCriterion("thumb is not null");
			return (Criteria) this;
		}

		public Criteria andThumbEqualTo(String value) {
			addCriterion("thumb =", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotEqualTo(String value) {
			addCriterion("thumb <>", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbGreaterThan(String value) {
			addCriterion("thumb >", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbGreaterThanOrEqualTo(String value) {
			addCriterion("thumb >=", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbLessThan(String value) {
			addCriterion("thumb <", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbLessThanOrEqualTo(String value) {
			addCriterion("thumb <=", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbLike(String value) {
			addCriterion("thumb like", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotLike(String value) {
			addCriterion("thumb not like", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbIn(List<String> values) {
			addCriterion("thumb in", values, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotIn(List<String> values) {
			addCriterion("thumb not in", values, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbBetween(String value1, String value2) {
			addCriterion("thumb between", value1, value2, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotBetween(String value1, String value2) {
			addCriterion("thumb not between", value1, value2, "thumb");
			return (Criteria) this;
		}

		public Criteria andImageIsNull() {
			addCriterion("image is null");
			return (Criteria) this;
		}

		public Criteria andImageIsNotNull() {
			addCriterion("image is not null");
			return (Criteria) this;
		}

		public Criteria andImageEqualTo(String value) {
			addCriterion("image =", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotEqualTo(String value) {
			addCriterion("image <>", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageGreaterThan(String value) {
			addCriterion("image >", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageGreaterThanOrEqualTo(String value) {
			addCriterion("image >=", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLessThan(String value) {
			addCriterion("image <", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLessThanOrEqualTo(String value) {
			addCriterion("image <=", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageLike(String value) {
			addCriterion("image like", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotLike(String value) {
			addCriterion("image not like", value, "image");
			return (Criteria) this;
		}

		public Criteria andImageIn(List<String> values) {
			addCriterion("image in", values, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotIn(List<String> values) {
			addCriterion("image not in", values, "image");
			return (Criteria) this;
		}

		public Criteria andImageBetween(String value1, String value2) {
			addCriterion("image between", value1, value2, "image");
			return (Criteria) this;
		}

		public Criteria andImageNotBetween(String value1, String value2) {
			addCriterion("image not between", value1, value2, "image");
			return (Criteria) this;
		}

		public Criteria andCat_codeIsNull() {
			addCriterion("cat_code is null");
			return (Criteria) this;
		}

		public Criteria andCat_codeIsNotNull() {
			addCriterion("cat_code is not null");
			return (Criteria) this;
		}

		public Criteria andCat_codeEqualTo(String value) {
			addCriterion("cat_code =", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeNotEqualTo(String value) {
			addCriterion("cat_code <>", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeGreaterThan(String value) {
			addCriterion("cat_code >", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeGreaterThanOrEqualTo(String value) {
			addCriterion("cat_code >=", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeLessThan(String value) {
			addCriterion("cat_code <", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeLessThanOrEqualTo(String value) {
			addCriterion("cat_code <=", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeLike(String value) {
			addCriterion("cat_code like", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeNotLike(String value) {
			addCriterion("cat_code not like", value, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeIn(List<String> values) {
			addCriterion("cat_code in", values, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeNotIn(List<String> values) {
			addCriterion("cat_code not in", values, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeBetween(String value1, String value2) {
			addCriterion("cat_code between", value1, value2, "cat_code");
			return (Criteria) this;
		}

		public Criteria andCat_codeNotBetween(String value1, String value2) {
			addCriterion("cat_code not between", value1, value2, "cat_code");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUser_idIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUser_idEqualTo(Long value) {
			addCriterion("user_id =", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThan(Long value) {
			addCriterion("user_id >", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThan(Long value) {
			addCriterion("user_id <", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idIn(List<Long> values) {
			addCriterion("user_id in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andUser_idNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "user_id");
			return (Criteria) this;
		}

		public Criteria andRecommendIsNull() {
			addCriterion("recommend is null");
			return (Criteria) this;
		}

		public Criteria andRecommendIsNotNull() {
			addCriterion("recommend is not null");
			return (Criteria) this;
		}

		public Criteria andRecommendEqualTo(String value) {
			addCriterion("recommend =", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotEqualTo(String value) {
			addCriterion("recommend <>", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendGreaterThan(String value) {
			addCriterion("recommend >", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendGreaterThanOrEqualTo(String value) {
			addCriterion("recommend >=", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendLessThan(String value) {
			addCriterion("recommend <", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendLessThanOrEqualTo(String value) {
			addCriterion("recommend <=", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendLike(String value) {
			addCriterion("recommend like", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotLike(String value) {
			addCriterion("recommend not like", value, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendIn(List<String> values) {
			addCriterion("recommend in", values, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotIn(List<String> values) {
			addCriterion("recommend not in", values, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendBetween(String value1, String value2) {
			addCriterion("recommend between", value1, value2, "recommend");
			return (Criteria) this;
		}

		public Criteria andRecommendNotBetween(String value1, String value2) {
			addCriterion("recommend not between", value1, value2, "recommend");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_category
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_category
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 05 15:49:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}