package com.ehais.school_weixin.model;

import java.util.ArrayList;
import java.util.List;

public class HaiHrPositionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public HaiHrPositionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPosition_idIsNull() {
			addCriterion("position_id is null");
			return (Criteria) this;
		}

		public Criteria andPosition_idIsNotNull() {
			addCriterion("position_id is not null");
			return (Criteria) this;
		}

		public Criteria andPosition_idEqualTo(Long value) {
			addCriterion("position_id =", value, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idNotEqualTo(Long value) {
			addCriterion("position_id <>", value, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idGreaterThan(Long value) {
			addCriterion("position_id >", value, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idGreaterThanOrEqualTo(Long value) {
			addCriterion("position_id >=", value, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idLessThan(Long value) {
			addCriterion("position_id <", value, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idLessThanOrEqualTo(Long value) {
			addCriterion("position_id <=", value, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idIn(List<Long> values) {
			addCriterion("position_id in", values, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idNotIn(List<Long> values) {
			addCriterion("position_id not in", values, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idBetween(Long value1, Long value2) {
			addCriterion("position_id between", value1, value2, "position_id");
			return (Criteria) this;
		}

		public Criteria andPosition_idNotBetween(Long value1, Long value2) {
			addCriterion("position_id not between", value1, value2, "position_id");
			return (Criteria) this;
		}

		public Criteria andCompany_nameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompany_nameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_nameEqualTo(String value) {
			addCriterion("company_name =", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameGreaterThan(String value) {
			addCriterion("company_name >", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameLessThan(String value) {
			addCriterion("company_name <", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameLike(String value) {
			addCriterion("company_name like", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameNotLike(String value) {
			addCriterion("company_name not like", value, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameIn(List<String> values) {
			addCriterion("company_name in", values, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "company_name");
			return (Criteria) this;
		}

		public Criteria andCompany_nameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "company_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameIsNull() {
			addCriterion("position_name is null");
			return (Criteria) this;
		}

		public Criteria andPosition_nameIsNotNull() {
			addCriterion("position_name is not null");
			return (Criteria) this;
		}

		public Criteria andPosition_nameEqualTo(String value) {
			addCriterion("position_name =", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameNotEqualTo(String value) {
			addCriterion("position_name <>", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameGreaterThan(String value) {
			addCriterion("position_name >", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameGreaterThanOrEqualTo(String value) {
			addCriterion("position_name >=", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameLessThan(String value) {
			addCriterion("position_name <", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameLessThanOrEqualTo(String value) {
			addCriterion("position_name <=", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameLike(String value) {
			addCriterion("position_name like", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameNotLike(String value) {
			addCriterion("position_name not like", value, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameIn(List<String> values) {
			addCriterion("position_name in", values, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameNotIn(List<String> values) {
			addCriterion("position_name not in", values, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameBetween(String value1, String value2) {
			addCriterion("position_name between", value1, value2, "position_name");
			return (Criteria) this;
		}

		public Criteria andPosition_nameNotBetween(String value1, String value2) {
			addCriterion("position_name not between", value1, value2, "position_name");
			return (Criteria) this;
		}

		public Criteria andWorkcityIsNull() {
			addCriterion("workcity is null");
			return (Criteria) this;
		}

		public Criteria andWorkcityIsNotNull() {
			addCriterion("workcity is not null");
			return (Criteria) this;
		}

		public Criteria andWorkcityEqualTo(String value) {
			addCriterion("workcity =", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityNotEqualTo(String value) {
			addCriterion("workcity <>", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityGreaterThan(String value) {
			addCriterion("workcity >", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityGreaterThanOrEqualTo(String value) {
			addCriterion("workcity >=", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityLessThan(String value) {
			addCriterion("workcity <", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityLessThanOrEqualTo(String value) {
			addCriterion("workcity <=", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityLike(String value) {
			addCriterion("workcity like", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityNotLike(String value) {
			addCriterion("workcity not like", value, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityIn(List<String> values) {
			addCriterion("workcity in", values, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityNotIn(List<String> values) {
			addCriterion("workcity not in", values, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityBetween(String value1, String value2) {
			addCriterion("workcity between", value1, value2, "workcity");
			return (Criteria) this;
		}

		public Criteria andWorkcityNotBetween(String value1, String value2) {
			addCriterion("workcity not between", value1, value2, "workcity");
			return (Criteria) this;
		}

		public Criteria andFulltimeIsNull() {
			addCriterion("fulltime is null");
			return (Criteria) this;
		}

		public Criteria andFulltimeIsNotNull() {
			addCriterion("fulltime is not null");
			return (Criteria) this;
		}

		public Criteria andFulltimeEqualTo(String value) {
			addCriterion("fulltime =", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeNotEqualTo(String value) {
			addCriterion("fulltime <>", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeGreaterThan(String value) {
			addCriterion("fulltime >", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeGreaterThanOrEqualTo(String value) {
			addCriterion("fulltime >=", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeLessThan(String value) {
			addCriterion("fulltime <", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeLessThanOrEqualTo(String value) {
			addCriterion("fulltime <=", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeLike(String value) {
			addCriterion("fulltime like", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeNotLike(String value) {
			addCriterion("fulltime not like", value, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeIn(List<String> values) {
			addCriterion("fulltime in", values, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeNotIn(List<String> values) {
			addCriterion("fulltime not in", values, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeBetween(String value1, String value2) {
			addCriterion("fulltime between", value1, value2, "fulltime");
			return (Criteria) this;
		}

		public Criteria andFulltimeNotBetween(String value1, String value2) {
			addCriterion("fulltime not between", value1, value2, "fulltime");
			return (Criteria) this;
		}

		public Criteria andPost_categoryIsNull() {
			addCriterion("post_category is null");
			return (Criteria) this;
		}

		public Criteria andPost_categoryIsNotNull() {
			addCriterion("post_category is not null");
			return (Criteria) this;
		}

		public Criteria andPost_categoryEqualTo(String value) {
			addCriterion("post_category =", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryNotEqualTo(String value) {
			addCriterion("post_category <>", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryGreaterThan(String value) {
			addCriterion("post_category >", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryGreaterThanOrEqualTo(String value) {
			addCriterion("post_category >=", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryLessThan(String value) {
			addCriterion("post_category <", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryLessThanOrEqualTo(String value) {
			addCriterion("post_category <=", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryLike(String value) {
			addCriterion("post_category like", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryNotLike(String value) {
			addCriterion("post_category not like", value, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryIn(List<String> values) {
			addCriterion("post_category in", values, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryNotIn(List<String> values) {
			addCriterion("post_category not in", values, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryBetween(String value1, String value2) {
			addCriterion("post_category between", value1, value2, "post_category");
			return (Criteria) this;
		}

		public Criteria andPost_categoryNotBetween(String value1, String value2) {
			addCriterion("post_category not between", value1, value2, "post_category");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNull() {
			addCriterion("industry is null");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNotNull() {
			addCriterion("industry is not null");
			return (Criteria) this;
		}

		public Criteria andIndustryEqualTo(String value) {
			addCriterion("industry =", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotEqualTo(String value) {
			addCriterion("industry <>", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThan(String value) {
			addCriterion("industry >", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThanOrEqualTo(String value) {
			addCriterion("industry >=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThan(String value) {
			addCriterion("industry <", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThanOrEqualTo(String value) {
			addCriterion("industry <=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLike(String value) {
			addCriterion("industry like", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotLike(String value) {
			addCriterion("industry not like", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryIn(List<String> values) {
			addCriterion("industry in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotIn(List<String> values) {
			addCriterion("industry not in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryBetween(String value1, String value2) {
			addCriterion("industry between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotBetween(String value1, String value2) {
			addCriterion("industry not between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andHeadcountIsNull() {
			addCriterion("headcount is null");
			return (Criteria) this;
		}

		public Criteria andHeadcountIsNotNull() {
			addCriterion("headcount is not null");
			return (Criteria) this;
		}

		public Criteria andHeadcountEqualTo(String value) {
			addCriterion("headcount =", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountNotEqualTo(String value) {
			addCriterion("headcount <>", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountGreaterThan(String value) {
			addCriterion("headcount >", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountGreaterThanOrEqualTo(String value) {
			addCriterion("headcount >=", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountLessThan(String value) {
			addCriterion("headcount <", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountLessThanOrEqualTo(String value) {
			addCriterion("headcount <=", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountLike(String value) {
			addCriterion("headcount like", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountNotLike(String value) {
			addCriterion("headcount not like", value, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountIn(List<String> values) {
			addCriterion("headcount in", values, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountNotIn(List<String> values) {
			addCriterion("headcount not in", values, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountBetween(String value1, String value2) {
			addCriterion("headcount between", value1, value2, "headcount");
			return (Criteria) this;
		}

		public Criteria andHeadcountNotBetween(String value1, String value2) {
			addCriterion("headcount not between", value1, value2, "headcount");
			return (Criteria) this;
		}

		public Criteria andDegreelevelIsNull() {
			addCriterion("degreelevel is null");
			return (Criteria) this;
		}

		public Criteria andDegreelevelIsNotNull() {
			addCriterion("degreelevel is not null");
			return (Criteria) this;
		}

		public Criteria andDegreelevelEqualTo(String value) {
			addCriterion("degreelevel =", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelNotEqualTo(String value) {
			addCriterion("degreelevel <>", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelGreaterThan(String value) {
			addCriterion("degreelevel >", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelGreaterThanOrEqualTo(String value) {
			addCriterion("degreelevel >=", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelLessThan(String value) {
			addCriterion("degreelevel <", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelLessThanOrEqualTo(String value) {
			addCriterion("degreelevel <=", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelLike(String value) {
			addCriterion("degreelevel like", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelNotLike(String value) {
			addCriterion("degreelevel not like", value, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelIn(List<String> values) {
			addCriterion("degreelevel in", values, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelNotIn(List<String> values) {
			addCriterion("degreelevel not in", values, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelBetween(String value1, String value2) {
			addCriterion("degreelevel between", value1, value2, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDegreelevelNotBetween(String value1, String value2) {
			addCriterion("degreelevel not between", value1, value2, "degreelevel");
			return (Criteria) this;
		}

		public Criteria andDepartmentIsNull() {
			addCriterion("department is null");
			return (Criteria) this;
		}

		public Criteria andDepartmentIsNotNull() {
			addCriterion("department is not null");
			return (Criteria) this;
		}

		public Criteria andDepartmentEqualTo(String value) {
			addCriterion("department =", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotEqualTo(String value) {
			addCriterion("department <>", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentGreaterThan(String value) {
			addCriterion("department >", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("department >=", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLessThan(String value) {
			addCriterion("department <", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLessThanOrEqualTo(String value) {
			addCriterion("department <=", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentLike(String value) {
			addCriterion("department like", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotLike(String value) {
			addCriterion("department not like", value, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentIn(List<String> values) {
			addCriterion("department in", values, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotIn(List<String> values) {
			addCriterion("department not in", values, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentBetween(String value1, String value2) {
			addCriterion("department between", value1, value2, "department");
			return (Criteria) this;
		}

		public Criteria andDepartmentNotBetween(String value1, String value2) {
			addCriterion("department not between", value1, value2, "department");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(String value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(String value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(String value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(String value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(String value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(String value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLike(String value) {
			addCriterion("gender like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotLike(String value) {
			addCriterion("gender not like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<String> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<String> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(String value1, String value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(String value1, String value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andWorkyearsIsNull() {
			addCriterion("workyears is null");
			return (Criteria) this;
		}

		public Criteria andWorkyearsIsNotNull() {
			addCriterion("workyears is not null");
			return (Criteria) this;
		}

		public Criteria andWorkyearsEqualTo(String value) {
			addCriterion("workyears =", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsNotEqualTo(String value) {
			addCriterion("workyears <>", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsGreaterThan(String value) {
			addCriterion("workyears >", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsGreaterThanOrEqualTo(String value) {
			addCriterion("workyears >=", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsLessThan(String value) {
			addCriterion("workyears <", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsLessThanOrEqualTo(String value) {
			addCriterion("workyears <=", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsLike(String value) {
			addCriterion("workyears like", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsNotLike(String value) {
			addCriterion("workyears not like", value, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsIn(List<String> values) {
			addCriterion("workyears in", values, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsNotIn(List<String> values) {
			addCriterion("workyears not in", values, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsBetween(String value1, String value2) {
			addCriterion("workyears between", value1, value2, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkyearsNotBetween(String value1, String value2) {
			addCriterion("workyears not between", value1, value2, "workyears");
			return (Criteria) this;
		}

		public Criteria andWorkagesIsNull() {
			addCriterion("workages is null");
			return (Criteria) this;
		}

		public Criteria andWorkagesIsNotNull() {
			addCriterion("workages is not null");
			return (Criteria) this;
		}

		public Criteria andWorkagesEqualTo(String value) {
			addCriterion("workages =", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesNotEqualTo(String value) {
			addCriterion("workages <>", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesGreaterThan(String value) {
			addCriterion("workages >", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesGreaterThanOrEqualTo(String value) {
			addCriterion("workages >=", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesLessThan(String value) {
			addCriterion("workages <", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesLessThanOrEqualTo(String value) {
			addCriterion("workages <=", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesLike(String value) {
			addCriterion("workages like", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesNotLike(String value) {
			addCriterion("workages not like", value, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesIn(List<String> values) {
			addCriterion("workages in", values, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesNotIn(List<String> values) {
			addCriterion("workages not in", values, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesBetween(String value1, String value2) {
			addCriterion("workages between", value1, value2, "workages");
			return (Criteria) this;
		}

		public Criteria andWorkagesNotBetween(String value1, String value2) {
			addCriterion("workages not between", value1, value2, "workages");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andContactpersonIsNull() {
			addCriterion("contactperson is null");
			return (Criteria) this;
		}

		public Criteria andContactpersonIsNotNull() {
			addCriterion("contactperson is not null");
			return (Criteria) this;
		}

		public Criteria andContactpersonEqualTo(String value) {
			addCriterion("contactperson =", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonNotEqualTo(String value) {
			addCriterion("contactperson <>", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonGreaterThan(String value) {
			addCriterion("contactperson >", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonGreaterThanOrEqualTo(String value) {
			addCriterion("contactperson >=", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonLessThan(String value) {
			addCriterion("contactperson <", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonLessThanOrEqualTo(String value) {
			addCriterion("contactperson <=", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonLike(String value) {
			addCriterion("contactperson like", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonNotLike(String value) {
			addCriterion("contactperson not like", value, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonIn(List<String> values) {
			addCriterion("contactperson in", values, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonNotIn(List<String> values) {
			addCriterion("contactperson not in", values, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonBetween(String value1, String value2) {
			addCriterion("contactperson between", value1, value2, "contactperson");
			return (Criteria) this;
		}

		public Criteria andContactpersonNotBetween(String value1, String value2) {
			addCriterion("contactperson not between", value1, value2, "contactperson");
			return (Criteria) this;
		}

		public Criteria andCompany_faxIsNull() {
			addCriterion("company_fax is null");
			return (Criteria) this;
		}

		public Criteria andCompany_faxIsNotNull() {
			addCriterion("company_fax is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_faxEqualTo(String value) {
			addCriterion("company_fax =", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxNotEqualTo(String value) {
			addCriterion("company_fax <>", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxGreaterThan(String value) {
			addCriterion("company_fax >", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxGreaterThanOrEqualTo(String value) {
			addCriterion("company_fax >=", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxLessThan(String value) {
			addCriterion("company_fax <", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxLessThanOrEqualTo(String value) {
			addCriterion("company_fax <=", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxLike(String value) {
			addCriterion("company_fax like", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxNotLike(String value) {
			addCriterion("company_fax not like", value, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxIn(List<String> values) {
			addCriterion("company_fax in", values, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxNotIn(List<String> values) {
			addCriterion("company_fax not in", values, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxBetween(String value1, String value2) {
			addCriterion("company_fax between", value1, value2, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_faxNotBetween(String value1, String value2) {
			addCriterion("company_fax not between", value1, value2, "company_fax");
			return (Criteria) this;
		}

		public Criteria andCompany_emailIsNull() {
			addCriterion("company_email is null");
			return (Criteria) this;
		}

		public Criteria andCompany_emailIsNotNull() {
			addCriterion("company_email is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_emailEqualTo(String value) {
			addCriterion("company_email =", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailNotEqualTo(String value) {
			addCriterion("company_email <>", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailGreaterThan(String value) {
			addCriterion("company_email >", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailGreaterThanOrEqualTo(String value) {
			addCriterion("company_email >=", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailLessThan(String value) {
			addCriterion("company_email <", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailLessThanOrEqualTo(String value) {
			addCriterion("company_email <=", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailLike(String value) {
			addCriterion("company_email like", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailNotLike(String value) {
			addCriterion("company_email not like", value, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailIn(List<String> values) {
			addCriterion("company_email in", values, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailNotIn(List<String> values) {
			addCriterion("company_email not in", values, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailBetween(String value1, String value2) {
			addCriterion("company_email between", value1, value2, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_emailNotBetween(String value1, String value2) {
			addCriterion("company_email not between", value1, value2, "company_email");
			return (Criteria) this;
		}

		public Criteria andCompany_addressIsNull() {
			addCriterion("company_address is null");
			return (Criteria) this;
		}

		public Criteria andCompany_addressIsNotNull() {
			addCriterion("company_address is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_addressEqualTo(String value) {
			addCriterion("company_address =", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressNotEqualTo(String value) {
			addCriterion("company_address <>", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressGreaterThan(String value) {
			addCriterion("company_address >", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressGreaterThanOrEqualTo(String value) {
			addCriterion("company_address >=", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressLessThan(String value) {
			addCriterion("company_address <", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressLessThanOrEqualTo(String value) {
			addCriterion("company_address <=", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressLike(String value) {
			addCriterion("company_address like", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressNotLike(String value) {
			addCriterion("company_address not like", value, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressIn(List<String> values) {
			addCriterion("company_address in", values, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressNotIn(List<String> values) {
			addCriterion("company_address not in", values, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressBetween(String value1, String value2) {
			addCriterion("company_address between", value1, value2, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_addressNotBetween(String value1, String value2) {
			addCriterion("company_address not between", value1, value2, "company_address");
			return (Criteria) this;
		}

		public Criteria andCompany_zipIsNull() {
			addCriterion("company_zip is null");
			return (Criteria) this;
		}

		public Criteria andCompany_zipIsNotNull() {
			addCriterion("company_zip is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_zipEqualTo(String value) {
			addCriterion("company_zip =", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipNotEqualTo(String value) {
			addCriterion("company_zip <>", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipGreaterThan(String value) {
			addCriterion("company_zip >", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipGreaterThanOrEqualTo(String value) {
			addCriterion("company_zip >=", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipLessThan(String value) {
			addCriterion("company_zip <", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipLessThanOrEqualTo(String value) {
			addCriterion("company_zip <=", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipLike(String value) {
			addCriterion("company_zip like", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipNotLike(String value) {
			addCriterion("company_zip not like", value, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipIn(List<String> values) {
			addCriterion("company_zip in", values, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipNotIn(List<String> values) {
			addCriterion("company_zip not in", values, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipBetween(String value1, String value2) {
			addCriterion("company_zip between", value1, value2, "company_zip");
			return (Criteria) this;
		}

		public Criteria andCompany_zipNotBetween(String value1, String value2) {
			addCriterion("company_zip not between", value1, value2, "company_zip");
			return (Criteria) this;
		}

		public Criteria andMarriageIsNull() {
			addCriterion("marriage is null");
			return (Criteria) this;
		}

		public Criteria andMarriageIsNotNull() {
			addCriterion("marriage is not null");
			return (Criteria) this;
		}

		public Criteria andMarriageEqualTo(String value) {
			addCriterion("marriage =", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageNotEqualTo(String value) {
			addCriterion("marriage <>", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageGreaterThan(String value) {
			addCriterion("marriage >", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageGreaterThanOrEqualTo(String value) {
			addCriterion("marriage >=", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageLessThan(String value) {
			addCriterion("marriage <", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageLessThanOrEqualTo(String value) {
			addCriterion("marriage <=", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageLike(String value) {
			addCriterion("marriage like", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageNotLike(String value) {
			addCriterion("marriage not like", value, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageIn(List<String> values) {
			addCriterion("marriage in", values, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageNotIn(List<String> values) {
			addCriterion("marriage not in", values, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageBetween(String value1, String value2) {
			addCriterion("marriage between", value1, value2, "marriage");
			return (Criteria) this;
		}

		public Criteria andMarriageNotBetween(String value1, String value2) {
			addCriterion("marriage not between", value1, value2, "marriage");
			return (Criteria) this;
		}

		public Criteria andMajorIsNull() {
			addCriterion("major is null");
			return (Criteria) this;
		}

		public Criteria andMajorIsNotNull() {
			addCriterion("major is not null");
			return (Criteria) this;
		}

		public Criteria andMajorEqualTo(String value) {
			addCriterion("major =", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotEqualTo(String value) {
			addCriterion("major <>", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThan(String value) {
			addCriterion("major >", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThanOrEqualTo(String value) {
			addCriterion("major >=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThan(String value) {
			addCriterion("major <", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThanOrEqualTo(String value) {
			addCriterion("major <=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLike(String value) {
			addCriterion("major like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotLike(String value) {
			addCriterion("major not like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorIn(List<String> values) {
			addCriterion("major in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotIn(List<String> values) {
			addCriterion("major not in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorBetween(String value1, String value2) {
			addCriterion("major between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotBetween(String value1, String value2) {
			addCriterion("major not between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andProfessionIsNull() {
			addCriterion("profession is null");
			return (Criteria) this;
		}

		public Criteria andProfessionIsNotNull() {
			addCriterion("profession is not null");
			return (Criteria) this;
		}

		public Criteria andProfessionEqualTo(String value) {
			addCriterion("profession =", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotEqualTo(String value) {
			addCriterion("profession <>", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionGreaterThan(String value) {
			addCriterion("profession >", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionGreaterThanOrEqualTo(String value) {
			addCriterion("profession >=", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLessThan(String value) {
			addCriterion("profession <", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLessThanOrEqualTo(String value) {
			addCriterion("profession <=", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLike(String value) {
			addCriterion("profession like", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotLike(String value) {
			addCriterion("profession not like", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionIn(List<String> values) {
			addCriterion("profession in", values, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotIn(List<String> values) {
			addCriterion("profession not in", values, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionBetween(String value1, String value2) {
			addCriterion("profession between", value1, value2, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotBetween(String value1, String value2) {
			addCriterion("profession not between", value1, value2, "profession");
			return (Criteria) this;
		}

		public Criteria andLanguageIsNull() {
			addCriterion("language is null");
			return (Criteria) this;
		}

		public Criteria andLanguageIsNotNull() {
			addCriterion("language is not null");
			return (Criteria) this;
		}

		public Criteria andLanguageEqualTo(String value) {
			addCriterion("language =", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotEqualTo(String value) {
			addCriterion("language <>", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageGreaterThan(String value) {
			addCriterion("language >", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageGreaterThanOrEqualTo(String value) {
			addCriterion("language >=", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageLessThan(String value) {
			addCriterion("language <", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageLessThanOrEqualTo(String value) {
			addCriterion("language <=", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageLike(String value) {
			addCriterion("language like", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotLike(String value) {
			addCriterion("language not like", value, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageIn(List<String> values) {
			addCriterion("language in", values, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotIn(List<String> values) {
			addCriterion("language not in", values, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageBetween(String value1, String value2) {
			addCriterion("language between", value1, value2, "language");
			return (Criteria) this;
		}

		public Criteria andLanguageNotBetween(String value1, String value2) {
			addCriterion("language not between", value1, value2, "language");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceIsNull() {
			addCriterion("interviewplace is null");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceIsNotNull() {
			addCriterion("interviewplace is not null");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceEqualTo(String value) {
			addCriterion("interviewplace =", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceNotEqualTo(String value) {
			addCriterion("interviewplace <>", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceGreaterThan(String value) {
			addCriterion("interviewplace >", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceGreaterThanOrEqualTo(String value) {
			addCriterion("interviewplace >=", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceLessThan(String value) {
			addCriterion("interviewplace <", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceLessThanOrEqualTo(String value) {
			addCriterion("interviewplace <=", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceLike(String value) {
			addCriterion("interviewplace like", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceNotLike(String value) {
			addCriterion("interviewplace not like", value, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceIn(List<String> values) {
			addCriterion("interviewplace in", values, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceNotIn(List<String> values) {
			addCriterion("interviewplace not in", values, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceBetween(String value1, String value2) {
			addCriterion("interviewplace between", value1, value2, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewplaceNotBetween(String value1, String value2) {
			addCriterion("interviewplace not between", value1, value2, "interviewplace");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeIsNull() {
			addCriterion("interviewtime is null");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeIsNotNull() {
			addCriterion("interviewtime is not null");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeEqualTo(String value) {
			addCriterion("interviewtime =", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeNotEqualTo(String value) {
			addCriterion("interviewtime <>", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeGreaterThan(String value) {
			addCriterion("interviewtime >", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeGreaterThanOrEqualTo(String value) {
			addCriterion("interviewtime >=", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeLessThan(String value) {
			addCriterion("interviewtime <", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeLessThanOrEqualTo(String value) {
			addCriterion("interviewtime <=", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeLike(String value) {
			addCriterion("interviewtime like", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeNotLike(String value) {
			addCriterion("interviewtime not like", value, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeIn(List<String> values) {
			addCriterion("interviewtime in", values, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeNotIn(List<String> values) {
			addCriterion("interviewtime not in", values, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeBetween(String value1, String value2) {
			addCriterion("interviewtime between", value1, value2, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andInterviewtimeNotBetween(String value1, String value2) {
			addCriterion("interviewtime not between", value1, value2, "interviewtime");
			return (Criteria) this;
		}

		public Criteria andIssue_timeIsNull() {
			addCriterion("issue_time is null");
			return (Criteria) this;
		}

		public Criteria andIssue_timeIsNotNull() {
			addCriterion("issue_time is not null");
			return (Criteria) this;
		}

		public Criteria andIssue_timeEqualTo(String value) {
			addCriterion("issue_time =", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeNotEqualTo(String value) {
			addCriterion("issue_time <>", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeGreaterThan(String value) {
			addCriterion("issue_time >", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeGreaterThanOrEqualTo(String value) {
			addCriterion("issue_time >=", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeLessThan(String value) {
			addCriterion("issue_time <", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeLessThanOrEqualTo(String value) {
			addCriterion("issue_time <=", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeLike(String value) {
			addCriterion("issue_time like", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeNotLike(String value) {
			addCriterion("issue_time not like", value, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeIn(List<String> values) {
			addCriterion("issue_time in", values, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeNotIn(List<String> values) {
			addCriterion("issue_time not in", values, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeBetween(String value1, String value2) {
			addCriterion("issue_time between", value1, value2, "issue_time");
			return (Criteria) this;
		}

		public Criteria andIssue_timeNotBetween(String value1, String value2) {
			addCriterion("issue_time not between", value1, value2, "issue_time");
			return (Criteria) this;
		}

		public Criteria andHeightbodyIsNull() {
			addCriterion("heightbody is null");
			return (Criteria) this;
		}

		public Criteria andHeightbodyIsNotNull() {
			addCriterion("heightbody is not null");
			return (Criteria) this;
		}

		public Criteria andHeightbodyEqualTo(String value) {
			addCriterion("heightbody =", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyNotEqualTo(String value) {
			addCriterion("heightbody <>", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyGreaterThan(String value) {
			addCriterion("heightbody >", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyGreaterThanOrEqualTo(String value) {
			addCriterion("heightbody >=", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyLessThan(String value) {
			addCriterion("heightbody <", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyLessThanOrEqualTo(String value) {
			addCriterion("heightbody <=", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyLike(String value) {
			addCriterion("heightbody like", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyNotLike(String value) {
			addCriterion("heightbody not like", value, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyIn(List<String> values) {
			addCriterion("heightbody in", values, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyNotIn(List<String> values) {
			addCriterion("heightbody not in", values, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyBetween(String value1, String value2) {
			addCriterion("heightbody between", value1, value2, "heightbody");
			return (Criteria) this;
		}

		public Criteria andHeightbodyNotBetween(String value1, String value2) {
			addCriterion("heightbody not between", value1, value2, "heightbody");
			return (Criteria) this;
		}

		public Criteria andCensusIsNull() {
			addCriterion("census is null");
			return (Criteria) this;
		}

		public Criteria andCensusIsNotNull() {
			addCriterion("census is not null");
			return (Criteria) this;
		}

		public Criteria andCensusEqualTo(String value) {
			addCriterion("census =", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusNotEqualTo(String value) {
			addCriterion("census <>", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusGreaterThan(String value) {
			addCriterion("census >", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusGreaterThanOrEqualTo(String value) {
			addCriterion("census >=", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusLessThan(String value) {
			addCriterion("census <", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusLessThanOrEqualTo(String value) {
			addCriterion("census <=", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusLike(String value) {
			addCriterion("census like", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusNotLike(String value) {
			addCriterion("census not like", value, "census");
			return (Criteria) this;
		}

		public Criteria andCensusIn(List<String> values) {
			addCriterion("census in", values, "census");
			return (Criteria) this;
		}

		public Criteria andCensusNotIn(List<String> values) {
			addCriterion("census not in", values, "census");
			return (Criteria) this;
		}

		public Criteria andCensusBetween(String value1, String value2) {
			addCriterion("census between", value1, value2, "census");
			return (Criteria) this;
		}

		public Criteria andCensusNotBetween(String value1, String value2) {
			addCriterion("census not between", value1, value2, "census");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostIsNull() {
			addCriterion("technicalpost is null");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostIsNotNull() {
			addCriterion("technicalpost is not null");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostEqualTo(String value) {
			addCriterion("technicalpost =", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostNotEqualTo(String value) {
			addCriterion("technicalpost <>", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostGreaterThan(String value) {
			addCriterion("technicalpost >", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostGreaterThanOrEqualTo(String value) {
			addCriterion("technicalpost >=", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostLessThan(String value) {
			addCriterion("technicalpost <", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostLessThanOrEqualTo(String value) {
			addCriterion("technicalpost <=", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostLike(String value) {
			addCriterion("technicalpost like", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostNotLike(String value) {
			addCriterion("technicalpost not like", value, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostIn(List<String> values) {
			addCriterion("technicalpost in", values, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostNotIn(List<String> values) {
			addCriterion("technicalpost not in", values, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostBetween(String value1, String value2) {
			addCriterion("technicalpost between", value1, value2, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andTechnicalpostNotBetween(String value1, String value2) {
			addCriterion("technicalpost not between", value1, value2, "technicalpost");
			return (Criteria) this;
		}

		public Criteria andWelfareIsNull() {
			addCriterion("welfare is null");
			return (Criteria) this;
		}

		public Criteria andWelfareIsNotNull() {
			addCriterion("welfare is not null");
			return (Criteria) this;
		}

		public Criteria andWelfareEqualTo(String value) {
			addCriterion("welfare =", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareNotEqualTo(String value) {
			addCriterion("welfare <>", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareGreaterThan(String value) {
			addCriterion("welfare >", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareGreaterThanOrEqualTo(String value) {
			addCriterion("welfare >=", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareLessThan(String value) {
			addCriterion("welfare <", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareLessThanOrEqualTo(String value) {
			addCriterion("welfare <=", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareLike(String value) {
			addCriterion("welfare like", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareNotLike(String value) {
			addCriterion("welfare not like", value, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareIn(List<String> values) {
			addCriterion("welfare in", values, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareNotIn(List<String> values) {
			addCriterion("welfare not in", values, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareBetween(String value1, String value2) {
			addCriterion("welfare between", value1, value2, "welfare");
			return (Criteria) this;
		}

		public Criteria andWelfareNotBetween(String value1, String value2) {
			addCriterion("welfare not between", value1, value2, "welfare");
			return (Criteria) this;
		}

		public Criteria andCompany_natureIsNull() {
			addCriterion("company_nature is null");
			return (Criteria) this;
		}

		public Criteria andCompany_natureIsNotNull() {
			addCriterion("company_nature is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_natureEqualTo(String value) {
			addCriterion("company_nature =", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureNotEqualTo(String value) {
			addCriterion("company_nature <>", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureGreaterThan(String value) {
			addCriterion("company_nature >", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureGreaterThanOrEqualTo(String value) {
			addCriterion("company_nature >=", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureLessThan(String value) {
			addCriterion("company_nature <", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureLessThanOrEqualTo(String value) {
			addCriterion("company_nature <=", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureLike(String value) {
			addCriterion("company_nature like", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureNotLike(String value) {
			addCriterion("company_nature not like", value, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureIn(List<String> values) {
			addCriterion("company_nature in", values, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureNotIn(List<String> values) {
			addCriterion("company_nature not in", values, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureBetween(String value1, String value2) {
			addCriterion("company_nature between", value1, value2, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_natureNotBetween(String value1, String value2) {
			addCriterion("company_nature not between", value1, value2, "company_nature");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleIsNull() {
			addCriterion("company_scale is null");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleIsNotNull() {
			addCriterion("company_scale is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleEqualTo(String value) {
			addCriterion("company_scale =", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleNotEqualTo(String value) {
			addCriterion("company_scale <>", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleGreaterThan(String value) {
			addCriterion("company_scale >", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleGreaterThanOrEqualTo(String value) {
			addCriterion("company_scale >=", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleLessThan(String value) {
			addCriterion("company_scale <", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleLessThanOrEqualTo(String value) {
			addCriterion("company_scale <=", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleLike(String value) {
			addCriterion("company_scale like", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleNotLike(String value) {
			addCriterion("company_scale not like", value, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleIn(List<String> values) {
			addCriterion("company_scale in", values, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleNotIn(List<String> values) {
			addCriterion("company_scale not in", values, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleBetween(String value1, String value2) {
			addCriterion("company_scale between", value1, value2, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_scaleNotBetween(String value1, String value2) {
			addCriterion("company_scale not between", value1, value2, "company_scale");
			return (Criteria) this;
		}

		public Criteria andCompany_industryIsNull() {
			addCriterion("company_industry is null");
			return (Criteria) this;
		}

		public Criteria andCompany_industryIsNotNull() {
			addCriterion("company_industry is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_industryEqualTo(String value) {
			addCriterion("company_industry =", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryNotEqualTo(String value) {
			addCriterion("company_industry <>", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryGreaterThan(String value) {
			addCriterion("company_industry >", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryGreaterThanOrEqualTo(String value) {
			addCriterion("company_industry >=", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryLessThan(String value) {
			addCriterion("company_industry <", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryLessThanOrEqualTo(String value) {
			addCriterion("company_industry <=", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryLike(String value) {
			addCriterion("company_industry like", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryNotLike(String value) {
			addCriterion("company_industry not like", value, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryIn(List<String> values) {
			addCriterion("company_industry in", values, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryNotIn(List<String> values) {
			addCriterion("company_industry not in", values, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryBetween(String value1, String value2) {
			addCriterion("company_industry between", value1, value2, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_industryNotBetween(String value1, String value2) {
			addCriterion("company_industry not between", value1, value2, "company_industry");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteIsNull() {
			addCriterion("company_website is null");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteIsNotNull() {
			addCriterion("company_website is not null");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteEqualTo(String value) {
			addCriterion("company_website =", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteNotEqualTo(String value) {
			addCriterion("company_website <>", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteGreaterThan(String value) {
			addCriterion("company_website >", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteGreaterThanOrEqualTo(String value) {
			addCriterion("company_website >=", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteLessThan(String value) {
			addCriterion("company_website <", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteLessThanOrEqualTo(String value) {
			addCriterion("company_website <=", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteLike(String value) {
			addCriterion("company_website like", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteNotLike(String value) {
			addCriterion("company_website not like", value, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteIn(List<String> values) {
			addCriterion("company_website in", values, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteNotIn(List<String> values) {
			addCriterion("company_website not in", values, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteBetween(String value1, String value2) {
			addCriterion("company_website between", value1, value2, "company_website");
			return (Criteria) this;
		}

		public Criteria andCompany_websiteNotBetween(String value1, String value2) {
			addCriterion("company_website not between", value1, value2, "company_website");
			return (Criteria) this;
		}

		public Criteria andHr_sourceIsNull() {
			addCriterion("hr_source is null");
			return (Criteria) this;
		}

		public Criteria andHr_sourceIsNotNull() {
			addCriterion("hr_source is not null");
			return (Criteria) this;
		}

		public Criteria andHr_sourceEqualTo(String value) {
			addCriterion("hr_source =", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceNotEqualTo(String value) {
			addCriterion("hr_source <>", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceGreaterThan(String value) {
			addCriterion("hr_source >", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceGreaterThanOrEqualTo(String value) {
			addCriterion("hr_source >=", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceLessThan(String value) {
			addCriterion("hr_source <", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceLessThanOrEqualTo(String value) {
			addCriterion("hr_source <=", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceLike(String value) {
			addCriterion("hr_source like", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceNotLike(String value) {
			addCriterion("hr_source not like", value, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceIn(List<String> values) {
			addCriterion("hr_source in", values, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceNotIn(List<String> values) {
			addCriterion("hr_source not in", values, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceBetween(String value1, String value2) {
			addCriterion("hr_source between", value1, value2, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_sourceNotBetween(String value1, String value2) {
			addCriterion("hr_source not between", value1, value2, "hr_source");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlIsNull() {
			addCriterion("hr_position_url is null");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlIsNotNull() {
			addCriterion("hr_position_url is not null");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlEqualTo(String value) {
			addCriterion("hr_position_url =", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlNotEqualTo(String value) {
			addCriterion("hr_position_url <>", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlGreaterThan(String value) {
			addCriterion("hr_position_url >", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlGreaterThanOrEqualTo(String value) {
			addCriterion("hr_position_url >=", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlLessThan(String value) {
			addCriterion("hr_position_url <", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlLessThanOrEqualTo(String value) {
			addCriterion("hr_position_url <=", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlLike(String value) {
			addCriterion("hr_position_url like", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlNotLike(String value) {
			addCriterion("hr_position_url not like", value, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlIn(List<String> values) {
			addCriterion("hr_position_url in", values, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlNotIn(List<String> values) {
			addCriterion("hr_position_url not in", values, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlBetween(String value1, String value2) {
			addCriterion("hr_position_url between", value1, value2, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andHr_position_urlNotBetween(String value1, String value2) {
			addCriterion("hr_position_url not between", value1, value2, "hr_position_url");
			return (Criteria) this;
		}

		public Criteria andSalaryIsNull() {
			addCriterion("salary is null");
			return (Criteria) this;
		}

		public Criteria andSalaryIsNotNull() {
			addCriterion("salary is not null");
			return (Criteria) this;
		}

		public Criteria andSalaryEqualTo(String value) {
			addCriterion("salary =", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryNotEqualTo(String value) {
			addCriterion("salary <>", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryGreaterThan(String value) {
			addCriterion("salary >", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryGreaterThanOrEqualTo(String value) {
			addCriterion("salary >=", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryLessThan(String value) {
			addCriterion("salary <", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryLessThanOrEqualTo(String value) {
			addCriterion("salary <=", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryLike(String value) {
			addCriterion("salary like", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryNotLike(String value) {
			addCriterion("salary not like", value, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryIn(List<String> values) {
			addCriterion("salary in", values, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryNotIn(List<String> values) {
			addCriterion("salary not in", values, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryBetween(String value1, String value2) {
			addCriterion("salary between", value1, value2, "salary");
			return (Criteria) this;
		}

		public Criteria andSalaryNotBetween(String value1, String value2) {
			addCriterion("salary not between", value1, value2, "salary");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hai_hr_position
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hai_hr_position
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 05 15:49:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}