package com.ehais.school_weixin.model;

import java.util.Date;

public class HaiKeywordsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_keywords.date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_keywords.searchengine
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String searchengine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_keywords.keyword
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String keyword;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_keywords.date
	 * @return  the value of hai_keywords.date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_keywords.date
	 * @param date  the value for hai_keywords.date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_keywords.searchengine
	 * @return  the value of hai_keywords.searchengine
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getSearchengine() {
		return searchengine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_keywords.searchengine
	 * @param searchengine  the value for hai_keywords.searchengine
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setSearchengine(String searchengine) {
		this.searchengine = searchengine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_keywords.keyword
	 * @return  the value of hai_keywords.keyword
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_keywords.keyword
	 * @param keyword  the value for hai_keywords.keyword
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}
}