package com.ehais.school_weixin.model;

public class HaiLinkGoods extends HaiLinkGoodsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_link_goods.is_double
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Boolean is_double;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_link_goods.is_double
	 * @return  the value of hai_link_goods.is_double
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Boolean getIs_double() {
		return is_double;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_link_goods.is_double
	 * @param is_double  the value for hai_link_goods.is_double
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setIs_double(Boolean is_double) {
		this.is_double = is_double;
	}
}