package com.ehais.school_weixin.model;

public class HaiMailTemplates {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.template_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Boolean template_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.template_code
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String template_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.is_html
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Boolean is_html;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.template_subject
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String template_subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.last_modify
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer last_modify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.last_send
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer last_send;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_mail_templates.template_content
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String template_content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.template_id
	 * @return  the value of hai_mail_templates.template_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Boolean getTemplate_id() {
		return template_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.template_id
	 * @param template_id  the value for hai_mail_templates.template_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setTemplate_id(Boolean template_id) {
		this.template_id = template_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.template_code
	 * @return  the value of hai_mail_templates.template_code
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getTemplate_code() {
		return template_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.template_code
	 * @param template_code  the value for hai_mail_templates.template_code
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setTemplate_code(String template_code) {
		this.template_code = template_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.is_html
	 * @return  the value of hai_mail_templates.is_html
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Boolean getIs_html() {
		return is_html;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.is_html
	 * @param is_html  the value for hai_mail_templates.is_html
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setIs_html(Boolean is_html) {
		this.is_html = is_html;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.template_subject
	 * @return  the value of hai_mail_templates.template_subject
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getTemplate_subject() {
		return template_subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.template_subject
	 * @param template_subject  the value for hai_mail_templates.template_subject
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setTemplate_subject(String template_subject) {
		this.template_subject = template_subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.last_modify
	 * @return  the value of hai_mail_templates.last_modify
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getLast_modify() {
		return last_modify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.last_modify
	 * @param last_modify  the value for hai_mail_templates.last_modify
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLast_modify(Integer last_modify) {
		this.last_modify = last_modify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.last_send
	 * @return  the value of hai_mail_templates.last_send
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getLast_send() {
		return last_send;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.last_send
	 * @param last_send  the value for hai_mail_templates.last_send
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLast_send(Integer last_send) {
		this.last_send = last_send;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.type
	 * @return  the value of hai_mail_templates.type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.type
	 * @param type  the value for hai_mail_templates.type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_mail_templates.template_content
	 * @return  the value of hai_mail_templates.template_content
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getTemplate_content() {
		return template_content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_mail_templates.template_content
	 * @param template_content  the value for hai_mail_templates.template_content
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setTemplate_content(String template_content) {
		this.template_content = template_content;
	}
}