package com.ehais.school_weixin.model;

import java.math.BigDecimal;

public class HaiPack {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_pack.pack_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Byte pack_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_pack.pack_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String pack_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_pack.pack_img
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String pack_img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_pack.pack_fee
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private BigDecimal pack_fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_pack.free_money
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short free_money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_pack.pack_desc
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String pack_desc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_pack.pack_id
	 * @return  the value of hai_pack.pack_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Byte getPack_id() {
		return pack_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_pack.pack_id
	 * @param pack_id  the value for hai_pack.pack_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPack_id(Byte pack_id) {
		this.pack_id = pack_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_pack.pack_name
	 * @return  the value of hai_pack.pack_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getPack_name() {
		return pack_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_pack.pack_name
	 * @param pack_name  the value for hai_pack.pack_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPack_name(String pack_name) {
		this.pack_name = pack_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_pack.pack_img
	 * @return  the value of hai_pack.pack_img
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getPack_img() {
		return pack_img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_pack.pack_img
	 * @param pack_img  the value for hai_pack.pack_img
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPack_img(String pack_img) {
		this.pack_img = pack_img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_pack.pack_fee
	 * @return  the value of hai_pack.pack_fee
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public BigDecimal getPack_fee() {
		return pack_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_pack.pack_fee
	 * @param pack_fee  the value for hai_pack.pack_fee
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPack_fee(BigDecimal pack_fee) {
		this.pack_fee = pack_fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_pack.free_money
	 * @return  the value of hai_pack.free_money
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getFree_money() {
		return free_money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_pack.free_money
	 * @param free_money  the value for hai_pack.free_money
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setFree_money(Short free_money) {
		this.free_money = free_money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_pack.pack_desc
	 * @return  the value of hai_pack.pack_desc
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getPack_desc() {
		return pack_desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_pack.pack_desc
	 * @param pack_desc  the value for hai_pack.pack_desc
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPack_desc(String pack_desc) {
		this.pack_desc = pack_desc;
	}
}