package com.ehais.school_weixin.model;

import java.math.BigDecimal;

public class HaiSnatchLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_snatch_log.log_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer log_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_snatch_log.snatch_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Byte snatch_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_snatch_log.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_snatch_log.bid_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private BigDecimal bid_price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_snatch_log.bid_time
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer bid_time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_snatch_log.log_id
	 * @return  the value of hai_snatch_log.log_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getLog_id() {
		return log_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_snatch_log.log_id
	 * @param log_id  the value for hai_snatch_log.log_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLog_id(Integer log_id) {
		this.log_id = log_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_snatch_log.snatch_id
	 * @return  the value of hai_snatch_log.snatch_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Byte getSnatch_id() {
		return snatch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_snatch_log.snatch_id
	 * @param snatch_id  the value for hai_snatch_log.snatch_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setSnatch_id(Byte snatch_id) {
		this.snatch_id = snatch_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_snatch_log.user_id
	 * @return  the value of hai_snatch_log.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_snatch_log.user_id
	 * @param user_id  the value for hai_snatch_log.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_snatch_log.bid_price
	 * @return  the value of hai_snatch_log.bid_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public BigDecimal getBid_price() {
		return bid_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_snatch_log.bid_price
	 * @param bid_price  the value for hai_snatch_log.bid_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setBid_price(BigDecimal bid_price) {
		this.bid_price = bid_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_snatch_log.bid_time
	 * @return  the value of hai_snatch_log.bid_time
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getBid_time() {
		return bid_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_snatch_log.bid_time
	 * @param bid_time  the value for hai_snatch_log.bid_time
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setBid_time(Integer bid_time) {
		this.bid_time = bid_time;
	}
}