package com.ehais.school_weixin.model;

public class HaiUserFeed {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.feed_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer feed_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.value_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer value_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.goods_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer goods_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.feed_type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Boolean feed_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.is_feed
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Boolean is_feed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_user_feed.store_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer store_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.feed_id
	 * @return  the value of hai_user_feed.feed_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getFeed_id() {
		return feed_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.feed_id
	 * @param feed_id  the value for hai_user_feed.feed_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setFeed_id(Integer feed_id) {
		this.feed_id = feed_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.user_id
	 * @return  the value of hai_user_feed.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.user_id
	 * @param user_id  the value for hai_user_feed.user_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.value_id
	 * @return  the value of hai_user_feed.value_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getValue_id() {
		return value_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.value_id
	 * @param value_id  the value for hai_user_feed.value_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setValue_id(Integer value_id) {
		this.value_id = value_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.goods_id
	 * @return  the value of hai_user_feed.goods_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getGoods_id() {
		return goods_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.goods_id
	 * @param goods_id  the value for hai_user_feed.goods_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setGoods_id(Integer goods_id) {
		this.goods_id = goods_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.feed_type
	 * @return  the value of hai_user_feed.feed_type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Boolean getFeed_type() {
		return feed_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.feed_type
	 * @param feed_type  the value for hai_user_feed.feed_type
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setFeed_type(Boolean feed_type) {
		this.feed_type = feed_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.is_feed
	 * @return  the value of hai_user_feed.is_feed
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Boolean getIs_feed() {
		return is_feed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.is_feed
	 * @param is_feed  the value for hai_user_feed.is_feed
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setIs_feed(Boolean is_feed) {
		this.is_feed = is_feed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_user_feed.store_id
	 * @return  the value of hai_user_feed.store_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getStore_id() {
		return store_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_user_feed.store_id
	 * @param store_id  the value for hai_user_feed.store_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setStore_id(Integer store_id) {
		this.store_id = store_id;
	}
}