package com.ehais.school_weixin.model;

public class HaiVoteOption {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_vote_option.option_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short option_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_vote_option.vote_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Short vote_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_vote_option.option_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String option_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_vote_option.option_count
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer option_count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hai_vote_option.option_order
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Byte option_order;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_vote_option.option_id
	 * @return  the value of hai_vote_option.option_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getOption_id() {
		return option_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_vote_option.option_id
	 * @param option_id  the value for hai_vote_option.option_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOption_id(Short option_id) {
		this.option_id = option_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_vote_option.vote_id
	 * @return  the value of hai_vote_option.vote_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Short getVote_id() {
		return vote_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_vote_option.vote_id
	 * @param vote_id  the value for hai_vote_option.vote_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setVote_id(Short vote_id) {
		this.vote_id = vote_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_vote_option.option_name
	 * @return  the value of hai_vote_option.option_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getOption_name() {
		return option_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_vote_option.option_name
	 * @param option_name  the value for hai_vote_option.option_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOption_name(String option_name) {
		this.option_name = option_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_vote_option.option_count
	 * @return  the value of hai_vote_option.option_count
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getOption_count() {
		return option_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_vote_option.option_count
	 * @param option_count  the value for hai_vote_option.option_count
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOption_count(Integer option_count) {
		this.option_count = option_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hai_vote_option.option_order
	 * @return  the value of hai_vote_option.option_order
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Byte getOption_order() {
		return option_order;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hai_vote_option.option_order
	 * @param option_order  the value for hai_vote_option.option_order
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setOption_order(Byte option_order) {
		this.option_order = option_order;
	}
}