package com.ehais.school_weixin.model;

import java.util.Date;

public class WyCustomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.customer_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer customer_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.customer_code
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String customer_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.customer_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String customer_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.member_level_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer member_level_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.customer_level_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer customer_level_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.customer_type_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer customer_type_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.customer_source_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer customer_source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.industry_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer industry_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.community_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer community_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.building_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer building_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.house_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer house_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.tel
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.fax
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.email
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.homepage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String homepage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.postcode
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String postcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.create_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_customer.update_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Date update_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.customer_id
	 * @return  the value of wy_customer.customer_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getCustomer_id() {
		return customer_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.customer_id
	 * @param customer_id  the value for wy_customer.customer_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCustomer_id(Integer customer_id) {
		this.customer_id = customer_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.customer_code
	 * @return  the value of wy_customer.customer_code
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getCustomer_code() {
		return customer_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.customer_code
	 * @param customer_code  the value for wy_customer.customer_code
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCustomer_code(String customer_code) {
		this.customer_code = customer_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.customer_name
	 * @return  the value of wy_customer.customer_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getCustomer_name() {
		return customer_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.customer_name
	 * @param customer_name  the value for wy_customer.customer_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCustomer_name(String customer_name) {
		this.customer_name = customer_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.member_level_id
	 * @return  the value of wy_customer.member_level_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getMember_level_id() {
		return member_level_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.member_level_id
	 * @param member_level_id  the value for wy_customer.member_level_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setMember_level_id(Integer member_level_id) {
		this.member_level_id = member_level_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.customer_level_id
	 * @return  the value of wy_customer.customer_level_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getCustomer_level_id() {
		return customer_level_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.customer_level_id
	 * @param customer_level_id  the value for wy_customer.customer_level_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCustomer_level_id(Integer customer_level_id) {
		this.customer_level_id = customer_level_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.customer_type_id
	 * @return  the value of wy_customer.customer_type_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getCustomer_type_id() {
		return customer_type_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.customer_type_id
	 * @param customer_type_id  the value for wy_customer.customer_type_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCustomer_type_id(Integer customer_type_id) {
		this.customer_type_id = customer_type_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.customer_source_id
	 * @return  the value of wy_customer.customer_source_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getCustomer_source_id() {
		return customer_source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.customer_source_id
	 * @param customer_source_id  the value for wy_customer.customer_source_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCustomer_source_id(Integer customer_source_id) {
		this.customer_source_id = customer_source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.industry_id
	 * @return  the value of wy_customer.industry_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getIndustry_id() {
		return industry_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.industry_id
	 * @param industry_id  the value for wy_customer.industry_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setIndustry_id(Integer industry_id) {
		this.industry_id = industry_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.community_id
	 * @return  the value of wy_customer.community_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getCommunity_id() {
		return community_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.community_id
	 * @param community_id  the value for wy_customer.community_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCommunity_id(Integer community_id) {
		this.community_id = community_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.building_id
	 * @return  the value of wy_customer.building_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getBuilding_id() {
		return building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.building_id
	 * @param building_id  the value for wy_customer.building_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setBuilding_id(Integer building_id) {
		this.building_id = building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.house_id
	 * @return  the value of wy_customer.house_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getHouse_id() {
		return house_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.house_id
	 * @param house_id  the value for wy_customer.house_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setHouse_id(Integer house_id) {
		this.house_id = house_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.tel
	 * @return  the value of wy_customer.tel
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.tel
	 * @param tel  the value for wy_customer.tel
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.fax
	 * @return  the value of wy_customer.fax
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.fax
	 * @param fax  the value for wy_customer.fax
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.email
	 * @return  the value of wy_customer.email
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.email
	 * @param email  the value for wy_customer.email
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.homepage
	 * @return  the value of wy_customer.homepage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getHomepage() {
		return homepage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.homepage
	 * @param homepage  the value for wy_customer.homepage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.postcode
	 * @return  the value of wy_customer.postcode
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getPostcode() {
		return postcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.postcode
	 * @param postcode  the value for wy_customer.postcode
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.address
	 * @return  the value of wy_customer.address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.address
	 * @param address  the value for wy_customer.address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.create_date
	 * @return  the value of wy_customer.create_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.create_date
	 * @param create_date  the value for wy_customer.create_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_customer.update_date
	 * @return  the value of wy_customer.update_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Date getUpdate_date() {
		return update_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_customer.update_date
	 * @param update_date  the value for wy_customer.update_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setUpdate_date(Date update_date) {
		this.update_date = update_date;
	}
}