package com.ehais.school_weixin.model;

import java.util.Date;

public class WyLiving {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.living_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer living_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.living_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Date living_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.end_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Date end_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.community_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer community_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.building_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer building_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.house_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer house_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.homeowner_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private Integer homeowner_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.homeowner_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String homeowner_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wy_living.remark
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.living_id
	 * @return  the value of wy_living.living_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getLiving_id() {
		return living_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.living_id
	 * @param living_id  the value for wy_living.living_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLiving_id(Integer living_id) {
		this.living_id = living_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.living_date
	 * @return  the value of wy_living.living_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Date getLiving_date() {
		return living_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.living_date
	 * @param living_date  the value for wy_living.living_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setLiving_date(Date living_date) {
		this.living_date = living_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.end_date
	 * @return  the value of wy_living.end_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Date getEnd_date() {
		return end_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.end_date
	 * @param end_date  the value for wy_living.end_date
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setEnd_date(Date end_date) {
		this.end_date = end_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.community_id
	 * @return  the value of wy_living.community_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getCommunity_id() {
		return community_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.community_id
	 * @param community_id  the value for wy_living.community_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setCommunity_id(Integer community_id) {
		this.community_id = community_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.building_id
	 * @return  the value of wy_living.building_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getBuilding_id() {
		return building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.building_id
	 * @param building_id  the value for wy_living.building_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setBuilding_id(Integer building_id) {
		this.building_id = building_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.house_id
	 * @return  the value of wy_living.house_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getHouse_id() {
		return house_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.house_id
	 * @param house_id  the value for wy_living.house_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setHouse_id(Integer house_id) {
		this.house_id = house_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.homeowner_id
	 * @return  the value of wy_living.homeowner_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public Integer getHomeowner_id() {
		return homeowner_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.homeowner_id
	 * @param homeowner_id  the value for wy_living.homeowner_id
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setHomeowner_id(Integer homeowner_id) {
		this.homeowner_id = homeowner_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.homeowner_name
	 * @return  the value of wy_living.homeowner_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getHomeowner_name() {
		return homeowner_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.homeowner_name
	 * @param homeowner_name  the value for wy_living.homeowner_name
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setHomeowner_name(String homeowner_name) {
		this.homeowner_name = homeowner_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wy_living.remark
	 * @return  the value of wy_living.remark
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wy_living.remark
	 * @param remark  the value for wy_living.remark
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}