package com.ehais.figoarticle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.ehais.figoarticle.model.Excel;
import com.ehais.figoarticle.model.ExcelExample;

public interface ExcelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    @Select("select count(*) from excel where #{field} = #{value} ")
    int unique(@Param("field") String field, @Param("value") String value);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    @Select("select count(*) from excel where #{field} = #{value} and store_id = #{store_id}")
    int uniqueStore(@Param("field") String field, @Param("value") String value, @Param("store_id") Integer store_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int countByExample(ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int deleteByExample(ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int insert(Excel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int insertSelective(Excel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    List<Excel> selectByExample(ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    Excel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") Excel record, @Param("example") ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int updateByExample(@Param("record") Excel record, @Param("example") ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int updateByPrimaryKeySelective(Excel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbggenerated Sun Mar 19 15:08:46 CST 2017
     */
    int updateByPrimaryKey(Excel record);
}