package com.ehais.figoarticle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import com.ehais.figoarticle.model.HaiCategory;
import com.ehais.figoarticle.model.HaiCategoryExample;
import com.ehais.figoarticle.model.WebSiteCount;

public interface HaiCategoryMapper {
	
	@Select("select count(*) as count,website_id from hai_category GROUP BY website_id")
	@Results(value = {  
            @Result(id = true, property = "count", column = "count", javaType = Integer.class, jdbcType = JdbcType.INTEGER),  
            @Result(property = "websiteId", column = "website_id", javaType = Integer.class, jdbcType = JdbcType.INTEGER) })
	public List<WebSiteCount> groupWebSite();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    long countByExample(HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int deleteByExample(HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int deleteByPrimaryKey(Integer catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int insert(HaiCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int insertSelective(HaiCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    List<HaiCategory> selectByExampleWithBLOBs(HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    List<HaiCategory> selectByExample(HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    HaiCategory selectByPrimaryKey(Integer catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiCategory record, @Param("example") HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") HaiCategory record, @Param("example") HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByExample(@Param("record") HaiCategory record, @Param("example") HaiCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByPrimaryKeySelective(HaiCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(HaiCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_category
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByPrimaryKey(HaiCategory record);
}