package com.ehais.figoarticle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ehais.figoarticle.model.HaiGoodsGallery;
import com.ehais.figoarticle.model.HaiGoodsGalleryExample;

public interface HaiGoodsGalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    long countByExample(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int deleteByExample(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int deleteByPrimaryKey(Long imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int insert(HaiGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int insertSelective(HaiGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    List<HaiGoodsGallery> selectByExample(HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    HaiGoodsGallery selectByPrimaryKey(Long imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") HaiGoodsGallery record, @Param("example") HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByExample(@Param("record") HaiGoodsGallery record, @Param("example") HaiGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByPrimaryKeySelective(HaiGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hai_goods_gallery
     *
     * @mbg.generated Fri Apr 14 21:52:06 CST 2017
     */
    int updateByPrimaryKey(HaiGoodsGallery record);
}