package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.CmfCommonActionLog;
import com.ehais.school_weixin.model.CmfCommonActionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmfCommonActionLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(CmfCommonActionLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(CmfCommonActionLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(CmfCommonActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(CmfCommonActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<CmfCommonActionLog> selectByExample(CmfCommonActionLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	CmfCommonActionLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CmfCommonActionLog record,
			@Param("example") CmfCommonActionLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") CmfCommonActionLog record,
			@Param("example") CmfCommonActionLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(CmfCommonActionLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_common_action_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(CmfCommonActionLog record);
}