package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.CmfPlugins;
import com.ehais.school_weixin.model.CmfPluginsExample;
import com.ehais.school_weixin.model.CmfPluginsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmfPluginsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(CmfPluginsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(CmfPluginsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<CmfPluginsWithBLOBs> selectByExampleWithBLOBs(CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<CmfPlugins> selectByExample(CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	CmfPluginsWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CmfPluginsWithBLOBs record,
			@Param("example") CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") CmfPluginsWithBLOBs record,
			@Param("example") CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") CmfPlugins record, @Param("example") CmfPluginsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(CmfPluginsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CmfPluginsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmf_plugins
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(CmfPlugins record);
}