package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiAutoManage;
import com.ehais.school_weixin.model.HaiAutoManageExample;
import com.ehais.school_weixin.model.HaiAutoManageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiAutoManageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiAutoManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiAutoManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(HaiAutoManageKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiAutoManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiAutoManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiAutoManage> selectByExample(HaiAutoManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiAutoManage selectByPrimaryKey(HaiAutoManageKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiAutoManage record, @Param("example") HaiAutoManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiAutoManage record, @Param("example") HaiAutoManageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiAutoManage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_auto_manage
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiAutoManage record);
}