package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiAreaRegionExample;
import com.ehais.school_weixin.model.HaiAreaRegionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiAreaRegionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiAreaRegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiAreaRegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(HaiAreaRegionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiAreaRegionKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiAreaRegionKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiAreaRegionKey> selectByExample(HaiAreaRegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiAreaRegionKey record,
			@Param("example") HaiAreaRegionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_area_region
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiAreaRegionKey record, @Param("example") HaiAreaRegionExample example);
}