package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiExchangeGoods;
import com.ehais.school_weixin.model.HaiExchangeGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiExchangeGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiExchangeGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiExchangeGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer goods_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiExchangeGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiExchangeGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiExchangeGoods> selectByExample(HaiExchangeGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiExchangeGoods selectByPrimaryKey(Integer goods_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiExchangeGoods record,
			@Param("example") HaiExchangeGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiExchangeGoods record, @Param("example") HaiExchangeGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiExchangeGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_exchange_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiExchangeGoods record);
}