package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiLinkGoods;
import com.ehais.school_weixin.model.HaiLinkGoodsExample;
import com.ehais.school_weixin.model.HaiLinkGoodsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiLinkGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiLinkGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiLinkGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(HaiLinkGoodsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiLinkGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiLinkGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiLinkGoods> selectByExample(HaiLinkGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiLinkGoods selectByPrimaryKey(HaiLinkGoodsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiLinkGoods record, @Param("example") HaiLinkGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiLinkGoods record, @Param("example") HaiLinkGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiLinkGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_link_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiLinkGoods record);
}