package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiOrderPayRecord;
import com.ehais.school_weixin.model.HaiOrderPayRecordExample;
import com.ehais.school_weixin.model.HaiOrderPayRecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiOrderPayRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Long order_pay_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiOrderPayRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiOrderPayRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiOrderPayRecordWithBLOBs> selectByExampleWithBLOBs(HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiOrderPayRecord> selectByExample(HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiOrderPayRecordWithBLOBs selectByPrimaryKey(Long order_pay_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiOrderPayRecordWithBLOBs record,
			@Param("example") HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") HaiOrderPayRecordWithBLOBs record,
			@Param("example") HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiOrderPayRecord record, @Param("example") HaiOrderPayRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiOrderPayRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(HaiOrderPayRecordWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_record
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiOrderPayRecord record);
}