package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiOrderPayExtends;
import com.ehais.school_weixin.model.HaiOrderPayExtendsExample;
import com.ehais.school_weixin.model.HaiOrderPayExtendsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiOrderPayExtendsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Long order_pay_extends_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiOrderPayExtendsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiOrderPayExtendsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiOrderPayExtendsWithBLOBs> selectByExampleWithBLOBs(HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiOrderPayExtends> selectByExample(HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiOrderPayExtendsWithBLOBs selectByPrimaryKey(Long order_pay_extends_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiOrderPayExtendsWithBLOBs record,
			@Param("example") HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") HaiOrderPayExtendsWithBLOBs record,
			@Param("example") HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiOrderPayExtends record,
			@Param("example") HaiOrderPayExtendsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiOrderPayExtendsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(HaiOrderPayExtendsWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_order_pay_extends
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiOrderPayExtends record);
}