package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiPayLog;
import com.ehais.school_weixin.model.HaiPayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiPayLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiPayLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiPayLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer log_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiPayLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiPayLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiPayLog> selectByExample(HaiPayLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiPayLog selectByPrimaryKey(Integer log_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiPayLog record, @Param("example") HaiPayLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiPayLog record, @Param("example") HaiPayLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiPayLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_pay_log
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiPayLog record);
}