package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiPackageGoods;
import com.ehais.school_weixin.model.HaiPackageGoodsExample;
import com.ehais.school_weixin.model.HaiPackageGoodsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiPackageGoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiPackageGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiPackageGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(HaiPackageGoodsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiPackageGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiPackageGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiPackageGoods> selectByExample(HaiPackageGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiPackageGoods selectByPrimaryKey(HaiPackageGoodsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiPackageGoods record,
			@Param("example") HaiPackageGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiPackageGoods record, @Param("example") HaiPackageGoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiPackageGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_package_goods
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiPackageGoods record);
}