package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiProducts;
import com.ehais.school_weixin.model.HaiProductsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiProductsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer product_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiProducts> selectByExample(HaiProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiProducts selectByPrimaryKey(Integer product_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiProducts record, @Param("example") HaiProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiProducts record, @Param("example") HaiProductsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_products
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiProducts record);
}