package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiRole;
import com.ehais.school_weixin.model.HaiRoleExample;
import com.ehais.school_weixin.model.HaiRoleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Short role_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiRoleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiRoleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiRoleWithBLOBs> selectByExampleWithBLOBs(HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiRole> selectByExample(HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiRoleWithBLOBs selectByPrimaryKey(Short role_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiRoleWithBLOBs record, @Param("example") HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") HaiRoleWithBLOBs record, @Param("example") HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiRole record, @Param("example") HaiRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiRoleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(HaiRoleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_role
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiRole record);
}