package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiShipping;
import com.ehais.school_weixin.model.HaiShippingExample;
import com.ehais.school_weixin.model.HaiShippingWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiShippingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Byte shipping_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiShippingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiShippingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiShippingWithBLOBs> selectByExampleWithBLOBs(HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiShipping> selectByExample(HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiShippingWithBLOBs selectByPrimaryKey(Byte shipping_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiShippingWithBLOBs record,
			@Param("example") HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") HaiShippingWithBLOBs record,
			@Param("example") HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiShipping record, @Param("example") HaiShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiShippingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(HaiShippingWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_shipping
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiShipping record);
}