package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiTranslationInfo;
import com.ehais.school_weixin.model.HaiTranslationInfoExample;
import com.ehais.school_weixin.model.HaiTranslationInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiTranslationInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer t_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiTranslationInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiTranslationInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiTranslationInfoWithBLOBs> selectByExampleWithBLOBs(HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiTranslationInfo> selectByExample(HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiTranslationInfoWithBLOBs selectByPrimaryKey(Integer t_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiTranslationInfoWithBLOBs record,
			@Param("example") HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") HaiTranslationInfoWithBLOBs record,
			@Param("example") HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiTranslationInfo record,
			@Param("example") HaiTranslationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiTranslationInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(HaiTranslationInfoWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_translation_info
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiTranslationInfo record);
}