package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiUserAddress;
import com.ehais.school_weixin.model.HaiUserAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiUserAddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiUserAddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiUserAddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer address_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiUserAddress> selectByExample(HaiUserAddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiUserAddress selectByPrimaryKey(Integer address_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiUserAddress record,
			@Param("example") HaiUserAddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiUserAddress record, @Param("example") HaiUserAddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_user_address
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiUserAddress record);
}