package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.HaiVolumePrice;
import com.ehais.school_weixin.model.HaiVolumePriceExample;
import com.ehais.school_weixin.model.HaiVolumePriceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HaiVolumePriceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(HaiVolumePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(HaiVolumePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(HaiVolumePriceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(HaiVolumePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(HaiVolumePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<HaiVolumePrice> selectByExample(HaiVolumePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	HaiVolumePrice selectByPrimaryKey(HaiVolumePriceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") HaiVolumePrice record,
			@Param("example") HaiVolumePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") HaiVolumePrice record, @Param("example") HaiVolumePriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(HaiVolumePrice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hai_volume_price
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(HaiVolumePrice record);
}