package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.ProProject;
import com.ehais.school_weixin.model.ProProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(ProProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(ProProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer pro_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(ProProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(ProProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<ProProject> selectByExample(ProProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	ProProject selectByPrimaryKey(Integer pro_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ProProject record, @Param("example") ProProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") ProProject record, @Param("example") ProProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(ProProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pro_project
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(ProProject record);
}