package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.ThinkAuthRule;
import com.ehais.school_weixin.model.ThinkAuthRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThinkAuthRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(ThinkAuthRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(ThinkAuthRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(ThinkAuthRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(ThinkAuthRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<ThinkAuthRule> selectByExample(ThinkAuthRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	ThinkAuthRule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ThinkAuthRule record, @Param("example") ThinkAuthRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") ThinkAuthRule record, @Param("example") ThinkAuthRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(ThinkAuthRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_rule
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(ThinkAuthRule record);
}