package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.ThinkAuthGroupAccess;
import com.ehais.school_weixin.model.ThinkAuthGroupAccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThinkAuthGroupAccessMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(ThinkAuthGroupAccessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(ThinkAuthGroupAccessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(ThinkAuthGroupAccess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(ThinkAuthGroupAccess record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<ThinkAuthGroupAccess> selectByExample(ThinkAuthGroupAccessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ThinkAuthGroupAccess record,
			@Param("example") ThinkAuthGroupAccessExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table think_auth_group_access
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") ThinkAuthGroupAccess record,
			@Param("example") ThinkAuthGroupAccessExample example);
}