package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.WpPublic;
import com.ehais.school_weixin.model.WpPublicExample;
import com.ehais.school_weixin.model.WpPublicWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WpPublicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(WpPublicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(WpPublicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<WpPublicWithBLOBs> selectByExampleWithBLOBs(WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<WpPublic> selectByExample(WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	WpPublicWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") WpPublicWithBLOBs record, @Param("example") WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") WpPublicWithBLOBs record, @Param("example") WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") WpPublic record, @Param("example") WpPublicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(WpPublicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(WpPublicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wp_public
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(WpPublic record);
}