package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.WxProfessional;
import com.ehais.school_weixin.model.WxProfessionalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxProfessionalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(WxProfessionalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(WxProfessionalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(WxProfessional record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(WxProfessional record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<WxProfessional> selectByExample(WxProfessionalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	WxProfessional selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") WxProfessional record,
			@Param("example") WxProfessionalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") WxProfessional record, @Param("example") WxProfessionalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(WxProfessional record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_professional
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(WxProfessional record);
}