package com.ehais.school_weixin.mapper;

import com.ehais.school_weixin.model.WySettingHouseDirection;
import com.ehais.school_weixin.model.WySettingHouseDirectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WySettingHouseDirectionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	long countByExample(WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByExample(WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int deleteByPrimaryKey(Integer setting_house_direction_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insert(WySettingHouseDirection record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int insertSelective(WySettingHouseDirection record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<WySettingHouseDirection> selectByExampleWithBLOBs(WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	List<WySettingHouseDirection> selectByExample(WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	WySettingHouseDirection selectByPrimaryKey(Integer setting_house_direction_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleSelective(@Param("record") WySettingHouseDirection record,
			@Param("example") WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") WySettingHouseDirection record,
			@Param("example") WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByExample(@Param("record") WySettingHouseDirection record,
			@Param("example") WySettingHouseDirectionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeySelective(WySettingHouseDirection record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(WySettingHouseDirection record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wy_setting_house_direction
	 * @mbg.generated  Mon Dec 05 15:58:20 CST 2016
	 */
	int updateByPrimaryKey(WySettingHouseDirection record);
}