package com.ehais.figoarticle.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class HaiGoods implements Serializable {
	
	private Boolean priceWarning;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.goods_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.cat_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.goods_sn
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.goods_name
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.brand_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.balance_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer balancePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.shop_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer shopPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.keywords
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.act_desc
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String actDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.goods_thumb
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String goodsThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.goods_img
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.original_img
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String originalImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.is_on_sale
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Boolean isOnSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.add_time
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.sort_order
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Short sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.last_update
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.exchangeRate
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private BigDecimal exchangerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.profit
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private BigDecimal profit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.shipping
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private BigDecimal shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.profitType
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer profittype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.currency
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.goods_url
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String goodsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.create_time
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.updated
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.created
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.deleted
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.website_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer websiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.attr_group
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String attrGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.stock
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.fid
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.buy_type
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer buyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.reserve_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Float reservePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.last_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Float lastPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.uv
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer uv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.pv
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer pv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.salesquantity
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer salesquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.local_thumb
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String localThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.category_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hai_goods.spider_source
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private String spiderSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hai_goods
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.goods_id
     *
     * @return the value of hai_goods.goods_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.goods_id
     *
     * @param goodsId the value for hai_goods.goods_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.cat_id
     *
     * @return the value of hai_goods.cat_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.cat_id
     *
     * @param catId the value for hai_goods.cat_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.goods_sn
     *
     * @return the value of hai_goods.goods_sn
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.goods_sn
     *
     * @param goodsSn the value for hai_goods.goods_sn
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.goods_name
     *
     * @return the value of hai_goods.goods_name
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.goods_name
     *
     * @param goodsName the value for hai_goods.goods_name
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.brand_id
     *
     * @return the value of hai_goods.brand_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.brand_id
     *
     * @param brandId the value for hai_goods.brand_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.balance_price
     *
     * @return the value of hai_goods.balance_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getBalancePrice() {
        return balancePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.balance_price
     *
     * @param balancePrice the value for hai_goods.balance_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setBalancePrice(Integer balancePrice) {
        this.balancePrice = balancePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.shop_price
     *
     * @return the value of hai_goods.shop_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.shop_price
     *
     * @param shopPrice the value for hai_goods.shop_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setShopPrice(Integer shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.keywords
     *
     * @return the value of hai_goods.keywords
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.keywords
     *
     * @param keywords the value for hai_goods.keywords
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.act_desc
     *
     * @return the value of hai_goods.act_desc
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getActDesc() {
        return actDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.act_desc
     *
     * @param actDesc the value for hai_goods.act_desc
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setActDesc(String actDesc) {
        this.actDesc = actDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.goods_thumb
     *
     * @return the value of hai_goods.goods_thumb
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getGoodsThumb() {
        return goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.goods_thumb
     *
     * @param goodsThumb the value for hai_goods.goods_thumb
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setGoodsThumb(String goodsThumb) {
        this.goodsThumb = goodsThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.goods_img
     *
     * @return the value of hai_goods.goods_img
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.goods_img
     *
     * @param goodsImg the value for hai_goods.goods_img
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.original_img
     *
     * @return the value of hai_goods.original_img
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getOriginalImg() {
        return originalImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.original_img
     *
     * @param originalImg the value for hai_goods.original_img
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setOriginalImg(String originalImg) {
        this.originalImg = originalImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.is_on_sale
     *
     * @return the value of hai_goods.is_on_sale
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Boolean getIsOnSale() {
        return isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.is_on_sale
     *
     * @param isOnSale the value for hai_goods.is_on_sale
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setIsOnSale(Boolean isOnSale) {
        this.isOnSale = isOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.add_time
     *
     * @return the value of hai_goods.add_time
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.add_time
     *
     * @param addTime the value for hai_goods.add_time
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.sort_order
     *
     * @return the value of hai_goods.sort_order
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Short getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.sort_order
     *
     * @param sortOrder the value for hai_goods.sort_order
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.last_update
     *
     * @return the value of hai_goods.last_update
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.last_update
     *
     * @param lastUpdate the value for hai_goods.last_update
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setLastUpdate(Integer lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.exchangeRate
     *
     * @return the value of hai_goods.exchangeRate
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public BigDecimal getExchangerate() {
        return exchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.exchangeRate
     *
     * @param exchangerate the value for hai_goods.exchangeRate
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setExchangerate(BigDecimal exchangerate) {
        this.exchangerate = exchangerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.profit
     *
     * @return the value of hai_goods.profit
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.profit
     *
     * @param profit the value for hai_goods.profit
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.shipping
     *
     * @return the value of hai_goods.shipping
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public BigDecimal getShipping() {
        return shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.shipping
     *
     * @param shipping the value for hai_goods.shipping
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.profitType
     *
     * @return the value of hai_goods.profitType
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getProfittype() {
        return profittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.profitType
     *
     * @param profittype the value for hai_goods.profitType
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setProfittype(Integer profittype) {
        this.profittype = profittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.currency
     *
     * @return the value of hai_goods.currency
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.currency
     *
     * @param currency the value for hai_goods.currency
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.goods_url
     *
     * @return the value of hai_goods.goods_url
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.goods_url
     *
     * @param goodsUrl the value for hai_goods.goods_url
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.create_time
     *
     * @return the value of hai_goods.create_time
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.create_time
     *
     * @param createTime the value for hai_goods.create_time
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.updated
     *
     * @return the value of hai_goods.updated
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.updated
     *
     * @param updated the value for hai_goods.updated
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.created
     *
     * @return the value of hai_goods.created
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.created
     *
     * @param created the value for hai_goods.created
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.deleted
     *
     * @return the value of hai_goods.deleted
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.deleted
     *
     * @param deleted the value for hai_goods.deleted
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.website_id
     *
     * @return the value of hai_goods.website_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.website_id
     *
     * @param websiteId the value for hai_goods.website_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.attr_group
     *
     * @return the value of hai_goods.attr_group
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getAttrGroup() {
        return attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.attr_group
     *
     * @param attrGroup the value for hai_goods.attr_group
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setAttrGroup(String attrGroup) {
        this.attrGroup = attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.stock
     *
     * @return the value of hai_goods.stock
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.stock
     *
     * @param stock the value for hai_goods.stock
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.fid
     *
     * @return the value of hai_goods.fid
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.fid
     *
     * @param fid the value for hai_goods.fid
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.buy_type
     *
     * @return the value of hai_goods.buy_type
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getBuyType() {
        return buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.buy_type
     *
     * @param buyType the value for hai_goods.buy_type
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setBuyType(Integer buyType) {
        this.buyType = buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.reserve_price
     *
     * @return the value of hai_goods.reserve_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Float getReservePrice() {
        return reservePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.reserve_price
     *
     * @param reservePrice the value for hai_goods.reserve_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setReservePrice(Float reservePrice) {
        this.reservePrice = reservePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.last_price
     *
     * @return the value of hai_goods.last_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Float getLastPrice() {
        return lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.last_price
     *
     * @param lastPrice the value for hai_goods.last_price
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setLastPrice(Float lastPrice) {
        this.lastPrice = lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.uv
     *
     * @return the value of hai_goods.uv
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.uv
     *
     * @param uv the value for hai_goods.uv
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setUv(Integer uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.pv
     *
     * @return the value of hai_goods.pv
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.pv
     *
     * @param pv the value for hai_goods.pv
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.salesquantity
     *
     * @return the value of hai_goods.salesquantity
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getSalesquantity() {
        return salesquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.salesquantity
     *
     * @param salesquantity the value for hai_goods.salesquantity
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setSalesquantity(Integer salesquantity) {
        this.salesquantity = salesquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.local_thumb
     *
     * @return the value of hai_goods.local_thumb
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getLocalThumb() {
        return localThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.local_thumb
     *
     * @param localThumb the value for hai_goods.local_thumb
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setLocalThumb(String localThumb) {
        this.localThumb = localThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.category_id
     *
     * @return the value of hai_goods.category_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.category_id
     *
     * @param categoryId the value for hai_goods.category_id
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hai_goods.spider_source
     *
     * @return the value of hai_goods.spider_source
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public String getSpiderSource() {
        return spiderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hai_goods.spider_source
     *
     * @param spiderSource the value for hai_goods.spider_source
     *
     * @mbg.generated Sun Nov 26 11:43:10 CST 2017
     */
    public void setSpiderSource(String spiderSource) {
        this.spiderSource = spiderSource;
    }
    
    public Boolean getPriceWarning() {
        return priceWarning;
    }

    public void setPriceWarning(Boolean priceWarning) {
        this.priceWarning = priceWarning;
    }
    
}